
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Domain: 'Domain',
  Tag: 'Tag',
  UserGoal: 'UserGoal',
  Roadmap: 'Roadmap',
  Checkpoint: 'Checkpoint',
  Question: 'Question',
  UserAnswer: 'UserAnswer',
  Session: 'Session',
  UserQuestionStats: 'UserQuestionStats',
  Payment: 'Payment',
  DomainEmbedding: 'DomainEmbedding',
  TagEmbedding: 'TagEmbedding'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  world_id: 'world_id',
  nickname: 'nickname',
  is_premium: 'is_premium',
  created_at: 'created_at',
  updated_at: 'updated_at'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const DomainScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  created_at: 'created_at'
} as const

export type DomainScalarFieldEnum = (typeof DomainScalarFieldEnum)[keyof typeof DomainScalarFieldEnum]


export const TagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  domain_id: 'domain_id',
  created_by: 'created_by',
  created_at: 'created_at'
} as const

export type TagScalarFieldEnum = (typeof TagScalarFieldEnum)[keyof typeof TagScalarFieldEnum]


export const UserGoalScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  domain_id: 'domain_id',
  target: 'target',
  level: 'level',
  is_active: 'is_active',
  created_at: 'created_at'
} as const

export type UserGoalScalarFieldEnum = (typeof UserGoalScalarFieldEnum)[keyof typeof UserGoalScalarFieldEnum]


export const RoadmapScalarFieldEnum = {
  id: 'id',
  goal_id: 'goal_id',
  title: 'title',
  is_template: 'is_template',
  created_at: 'created_at'
} as const

export type RoadmapScalarFieldEnum = (typeof RoadmapScalarFieldEnum)[keyof typeof RoadmapScalarFieldEnum]


export const CheckpointScalarFieldEnum = {
  id: 'id',
  roadmap_id: 'roadmap_id',
  title: 'title',
  description: 'description',
  tag_id: 'tag_id',
  difficulty: 'difficulty',
  order: 'order',
  status: 'status',
  best_score: 'best_score',
  attempts: 'attempts'
} as const

export type CheckpointScalarFieldEnum = (typeof CheckpointScalarFieldEnum)[keyof typeof CheckpointScalarFieldEnum]


export const QuestionScalarFieldEnum = {
  id: 'id',
  tag_id: 'tag_id',
  type: 'type',
  difficulty: 'difficulty',
  content: 'content',
  options: 'options',
  answer: 'answer',
  explanation: 'explanation',
  rubric: 'rubric',
  max_score: 'max_score',
  created_at: 'created_at'
} as const

export type QuestionScalarFieldEnum = (typeof QuestionScalarFieldEnum)[keyof typeof QuestionScalarFieldEnum]


export const UserAnswerScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  question_id: 'question_id',
  session_id: 'session_id',
  user_answer: 'user_answer',
  is_correct: 'is_correct',
  score: 'score',
  grade_reason: 'grade_reason',
  answered_at: 'answered_at'
} as const

export type UserAnswerScalarFieldEnum = (typeof UserAnswerScalarFieldEnum)[keyof typeof UserAnswerScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  checkpoint_id: 'checkpoint_id',
  score: 'score',
  total: 'total',
  correct: 'correct',
  status: 'status',
  created_at: 'created_at',
  completed_at: 'completed_at'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const UserQuestionStatsScalarFieldEnum = {
  user_id: 'user_id',
  question_id: 'question_id',
  total_attempts: 'total_attempts',
  correct_count: 'correct_count',
  last_seen_at: 'last_seen_at',
  half_life: 'half_life'
} as const

export type UserQuestionStatsScalarFieldEnum = (typeof UserQuestionStatsScalarFieldEnum)[keyof typeof UserQuestionStatsScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  tx_hash: 'tx_hash',
  amount_wld: 'amount_wld',
  product_type: 'product_type',
  status: 'status',
  created_at: 'created_at'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const DomainEmbeddingScalarFieldEnum = {
  id: 'id',
  domain_id: 'domain_id',
  created_at: 'created_at'
} as const

export type DomainEmbeddingScalarFieldEnum = (typeof DomainEmbeddingScalarFieldEnum)[keyof typeof DomainEmbeddingScalarFieldEnum]


export const TagEmbeddingScalarFieldEnum = {
  id: 'id',
  tag_id: 'tag_id',
  created_at: 'created_at'
} as const

export type TagEmbeddingScalarFieldEnum = (typeof TagEmbeddingScalarFieldEnum)[keyof typeof TagEmbeddingScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

