
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Domain
 * 
 */
export type Domain = Prisma.DomainModel
/**
 * Model Tag
 * 
 */
export type Tag = Prisma.TagModel
/**
 * Model UserGoal
 * 
 */
export type UserGoal = Prisma.UserGoalModel
/**
 * Model Roadmap
 * 
 */
export type Roadmap = Prisma.RoadmapModel
/**
 * Model Checkpoint
 * 
 */
export type Checkpoint = Prisma.CheckpointModel
/**
 * Model Question
 * 
 */
export type Question = Prisma.QuestionModel
/**
 * Model UserAnswer
 * 
 */
export type UserAnswer = Prisma.UserAnswerModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model UserQuestionStats
 * 
 */
export type UserQuestionStats = Prisma.UserQuestionStatsModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model DomainEmbedding
 * 
 */
export type DomainEmbedding = Prisma.DomainEmbeddingModel
/**
 * Model TagEmbedding
 * 
 */
export type TagEmbedding = Prisma.TagEmbeddingModel
