
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AuthProvider = {
  google: 'google',
  apple: 'apple',
  kakao: 'kakao',
  dev: 'dev',
  legacy_world: 'legacy_world'
} as const

export type AuthProvider = (typeof AuthProvider)[keyof typeof AuthProvider]


export const PaymentStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  failed: 'failed'
} as const

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus]
