
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Checkpoint` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Checkpoint
 * 
 */
export type CheckpointModel = runtime.Types.Result.DefaultSelection<Prisma.$CheckpointPayload>

export type AggregateCheckpoint = {
  _count: CheckpointCountAggregateOutputType | null
  _avg: CheckpointAvgAggregateOutputType | null
  _sum: CheckpointSumAggregateOutputType | null
  _min: CheckpointMinAggregateOutputType | null
  _max: CheckpointMaxAggregateOutputType | null
}

export type CheckpointAvgAggregateOutputType = {
  difficulty: number | null
  order: number | null
  best_score: number | null
  attempts: number | null
}

export type CheckpointSumAggregateOutputType = {
  difficulty: number | null
  order: number | null
  best_score: number | null
  attempts: number | null
}

export type CheckpointMinAggregateOutputType = {
  id: string | null
  roadmap_id: string | null
  title: string | null
  description: string | null
  tag_id: string | null
  difficulty: number | null
  order: number | null
  status: string | null
  best_score: number | null
  attempts: number | null
}

export type CheckpointMaxAggregateOutputType = {
  id: string | null
  roadmap_id: string | null
  title: string | null
  description: string | null
  tag_id: string | null
  difficulty: number | null
  order: number | null
  status: string | null
  best_score: number | null
  attempts: number | null
}

export type CheckpointCountAggregateOutputType = {
  id: number
  roadmap_id: number
  title: number
  description: number
  tag_id: number
  difficulty: number
  order: number
  status: number
  best_score: number
  attempts: number
  _all: number
}


export type CheckpointAvgAggregateInputType = {
  difficulty?: true
  order?: true
  best_score?: true
  attempts?: true
}

export type CheckpointSumAggregateInputType = {
  difficulty?: true
  order?: true
  best_score?: true
  attempts?: true
}

export type CheckpointMinAggregateInputType = {
  id?: true
  roadmap_id?: true
  title?: true
  description?: true
  tag_id?: true
  difficulty?: true
  order?: true
  status?: true
  best_score?: true
  attempts?: true
}

export type CheckpointMaxAggregateInputType = {
  id?: true
  roadmap_id?: true
  title?: true
  description?: true
  tag_id?: true
  difficulty?: true
  order?: true
  status?: true
  best_score?: true
  attempts?: true
}

export type CheckpointCountAggregateInputType = {
  id?: true
  roadmap_id?: true
  title?: true
  description?: true
  tag_id?: true
  difficulty?: true
  order?: true
  status?: true
  best_score?: true
  attempts?: true
  _all?: true
}

export type CheckpointAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Checkpoint to aggregate.
   */
  where?: Prisma.CheckpointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checkpoints to fetch.
   */
  orderBy?: Prisma.CheckpointOrderByWithRelationInput | Prisma.CheckpointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CheckpointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checkpoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checkpoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Checkpoints
  **/
  _count?: true | CheckpointCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CheckpointAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CheckpointSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CheckpointMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CheckpointMaxAggregateInputType
}

export type GetCheckpointAggregateType<T extends CheckpointAggregateArgs> = {
      [P in keyof T & keyof AggregateCheckpoint]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCheckpoint[P]>
    : Prisma.GetScalarType<T[P], AggregateCheckpoint[P]>
}




export type CheckpointGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CheckpointWhereInput
  orderBy?: Prisma.CheckpointOrderByWithAggregationInput | Prisma.CheckpointOrderByWithAggregationInput[]
  by: Prisma.CheckpointScalarFieldEnum[] | Prisma.CheckpointScalarFieldEnum
  having?: Prisma.CheckpointScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CheckpointCountAggregateInputType | true
  _avg?: CheckpointAvgAggregateInputType
  _sum?: CheckpointSumAggregateInputType
  _min?: CheckpointMinAggregateInputType
  _max?: CheckpointMaxAggregateInputType
}

export type CheckpointGroupByOutputType = {
  id: string
  roadmap_id: string
  title: string
  description: string | null
  tag_id: string
  difficulty: number
  order: number
  status: string
  best_score: number | null
  attempts: number
  _count: CheckpointCountAggregateOutputType | null
  _avg: CheckpointAvgAggregateOutputType | null
  _sum: CheckpointSumAggregateOutputType | null
  _min: CheckpointMinAggregateOutputType | null
  _max: CheckpointMaxAggregateOutputType | null
}

export type GetCheckpointGroupByPayload<T extends CheckpointGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CheckpointGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CheckpointGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CheckpointGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CheckpointGroupByOutputType[P]>
      }
    >
  >



export type CheckpointWhereInput = {
  AND?: Prisma.CheckpointWhereInput | Prisma.CheckpointWhereInput[]
  OR?: Prisma.CheckpointWhereInput[]
  NOT?: Prisma.CheckpointWhereInput | Prisma.CheckpointWhereInput[]
  id?: Prisma.UuidFilter<"Checkpoint"> | string
  roadmap_id?: Prisma.UuidFilter<"Checkpoint"> | string
  title?: Prisma.StringFilter<"Checkpoint"> | string
  description?: Prisma.StringNullableFilter<"Checkpoint"> | string | null
  tag_id?: Prisma.UuidFilter<"Checkpoint"> | string
  difficulty?: Prisma.IntFilter<"Checkpoint"> | number
  order?: Prisma.IntFilter<"Checkpoint"> | number
  status?: Prisma.StringFilter<"Checkpoint"> | string
  best_score?: Prisma.FloatNullableFilter<"Checkpoint"> | number | null
  attempts?: Prisma.IntFilter<"Checkpoint"> | number
  roadmap?: Prisma.XOR<Prisma.RoadmapScalarRelationFilter, Prisma.RoadmapWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
  sessions?: Prisma.SessionListRelationFilter
}

export type CheckpointOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  roadmap_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  order?: Prisma.SortOrder
  status?: Prisma.SortOrder
  best_score?: Prisma.SortOrderInput | Prisma.SortOrder
  attempts?: Prisma.SortOrder
  roadmap?: Prisma.RoadmapOrderByWithRelationInput
  tag?: Prisma.TagOrderByWithRelationInput
  sessions?: Prisma.SessionOrderByRelationAggregateInput
}

export type CheckpointWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CheckpointWhereInput | Prisma.CheckpointWhereInput[]
  OR?: Prisma.CheckpointWhereInput[]
  NOT?: Prisma.CheckpointWhereInput | Prisma.CheckpointWhereInput[]
  roadmap_id?: Prisma.UuidFilter<"Checkpoint"> | string
  title?: Prisma.StringFilter<"Checkpoint"> | string
  description?: Prisma.StringNullableFilter<"Checkpoint"> | string | null
  tag_id?: Prisma.UuidFilter<"Checkpoint"> | string
  difficulty?: Prisma.IntFilter<"Checkpoint"> | number
  order?: Prisma.IntFilter<"Checkpoint"> | number
  status?: Prisma.StringFilter<"Checkpoint"> | string
  best_score?: Prisma.FloatNullableFilter<"Checkpoint"> | number | null
  attempts?: Prisma.IntFilter<"Checkpoint"> | number
  roadmap?: Prisma.XOR<Prisma.RoadmapScalarRelationFilter, Prisma.RoadmapWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
  sessions?: Prisma.SessionListRelationFilter
}, "id">

export type CheckpointOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  roadmap_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  order?: Prisma.SortOrder
  status?: Prisma.SortOrder
  best_score?: Prisma.SortOrderInput | Prisma.SortOrder
  attempts?: Prisma.SortOrder
  _count?: Prisma.CheckpointCountOrderByAggregateInput
  _avg?: Prisma.CheckpointAvgOrderByAggregateInput
  _max?: Prisma.CheckpointMaxOrderByAggregateInput
  _min?: Prisma.CheckpointMinOrderByAggregateInput
  _sum?: Prisma.CheckpointSumOrderByAggregateInput
}

export type CheckpointScalarWhereWithAggregatesInput = {
  AND?: Prisma.CheckpointScalarWhereWithAggregatesInput | Prisma.CheckpointScalarWhereWithAggregatesInput[]
  OR?: Prisma.CheckpointScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CheckpointScalarWhereWithAggregatesInput | Prisma.CheckpointScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"Checkpoint"> | string
  roadmap_id?: Prisma.UuidWithAggregatesFilter<"Checkpoint"> | string
  title?: Prisma.StringWithAggregatesFilter<"Checkpoint"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Checkpoint"> | string | null
  tag_id?: Prisma.UuidWithAggregatesFilter<"Checkpoint"> | string
  difficulty?: Prisma.IntWithAggregatesFilter<"Checkpoint"> | number
  order?: Prisma.IntWithAggregatesFilter<"Checkpoint"> | number
  status?: Prisma.StringWithAggregatesFilter<"Checkpoint"> | string
  best_score?: Prisma.FloatNullableWithAggregatesFilter<"Checkpoint"> | number | null
  attempts?: Prisma.IntWithAggregatesFilter<"Checkpoint"> | number
}

export type CheckpointCreateInput = {
  id?: string
  title: string
  description?: string | null
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
  roadmap: Prisma.RoadmapCreateNestedOneWithoutCheckpointsInput
  tag: Prisma.TagCreateNestedOneWithoutCheckpointsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutCheckpointInput
}

export type CheckpointUncheckedCreateInput = {
  id?: string
  roadmap_id: string
  title: string
  description?: string | null
  tag_id: string
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutCheckpointInput
}

export type CheckpointUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  roadmap?: Prisma.RoadmapUpdateOneRequiredWithoutCheckpointsNestedInput
  tag?: Prisma.TagUpdateOneRequiredWithoutCheckpointsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutCheckpointNestedInput
}

export type CheckpointUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roadmap_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tag_id?: Prisma.StringFieldUpdateOperationsInput | string
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutCheckpointNestedInput
}

export type CheckpointCreateManyInput = {
  id?: string
  roadmap_id: string
  title: string
  description?: string | null
  tag_id: string
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
}

export type CheckpointUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CheckpointUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roadmap_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tag_id?: Prisma.StringFieldUpdateOperationsInput | string
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CheckpointListRelationFilter = {
  every?: Prisma.CheckpointWhereInput
  some?: Prisma.CheckpointWhereInput
  none?: Prisma.CheckpointWhereInput
}

export type CheckpointOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CheckpointCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  roadmap_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  order?: Prisma.SortOrder
  status?: Prisma.SortOrder
  best_score?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
}

export type CheckpointAvgOrderByAggregateInput = {
  difficulty?: Prisma.SortOrder
  order?: Prisma.SortOrder
  best_score?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
}

export type CheckpointMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  roadmap_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  order?: Prisma.SortOrder
  status?: Prisma.SortOrder
  best_score?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
}

export type CheckpointMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  roadmap_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  difficulty?: Prisma.SortOrder
  order?: Prisma.SortOrder
  status?: Prisma.SortOrder
  best_score?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
}

export type CheckpointSumOrderByAggregateInput = {
  difficulty?: Prisma.SortOrder
  order?: Prisma.SortOrder
  best_score?: Prisma.SortOrder
  attempts?: Prisma.SortOrder
}

export type CheckpointScalarRelationFilter = {
  is?: Prisma.CheckpointWhereInput
  isNot?: Prisma.CheckpointWhereInput
}

export type CheckpointCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutTagInput, Prisma.CheckpointUncheckedCreateWithoutTagInput> | Prisma.CheckpointCreateWithoutTagInput[] | Prisma.CheckpointUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutTagInput | Prisma.CheckpointCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.CheckpointCreateManyTagInputEnvelope
  connect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
}

export type CheckpointUncheckedCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutTagInput, Prisma.CheckpointUncheckedCreateWithoutTagInput> | Prisma.CheckpointCreateWithoutTagInput[] | Prisma.CheckpointUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutTagInput | Prisma.CheckpointCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.CheckpointCreateManyTagInputEnvelope
  connect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
}

export type CheckpointUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutTagInput, Prisma.CheckpointUncheckedCreateWithoutTagInput> | Prisma.CheckpointCreateWithoutTagInput[] | Prisma.CheckpointUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutTagInput | Prisma.CheckpointCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.CheckpointUpsertWithWhereUniqueWithoutTagInput | Prisma.CheckpointUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.CheckpointCreateManyTagInputEnvelope
  set?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  disconnect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  delete?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  connect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  update?: Prisma.CheckpointUpdateWithWhereUniqueWithoutTagInput | Prisma.CheckpointUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.CheckpointUpdateManyWithWhereWithoutTagInput | Prisma.CheckpointUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.CheckpointScalarWhereInput | Prisma.CheckpointScalarWhereInput[]
}

export type CheckpointUncheckedUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutTagInput, Prisma.CheckpointUncheckedCreateWithoutTagInput> | Prisma.CheckpointCreateWithoutTagInput[] | Prisma.CheckpointUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutTagInput | Prisma.CheckpointCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.CheckpointUpsertWithWhereUniqueWithoutTagInput | Prisma.CheckpointUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.CheckpointCreateManyTagInputEnvelope
  set?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  disconnect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  delete?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  connect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  update?: Prisma.CheckpointUpdateWithWhereUniqueWithoutTagInput | Prisma.CheckpointUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.CheckpointUpdateManyWithWhereWithoutTagInput | Prisma.CheckpointUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.CheckpointScalarWhereInput | Prisma.CheckpointScalarWhereInput[]
}

export type CheckpointCreateNestedManyWithoutRoadmapInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutRoadmapInput, Prisma.CheckpointUncheckedCreateWithoutRoadmapInput> | Prisma.CheckpointCreateWithoutRoadmapInput[] | Prisma.CheckpointUncheckedCreateWithoutRoadmapInput[]
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutRoadmapInput | Prisma.CheckpointCreateOrConnectWithoutRoadmapInput[]
  createMany?: Prisma.CheckpointCreateManyRoadmapInputEnvelope
  connect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
}

export type CheckpointUncheckedCreateNestedManyWithoutRoadmapInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutRoadmapInput, Prisma.CheckpointUncheckedCreateWithoutRoadmapInput> | Prisma.CheckpointCreateWithoutRoadmapInput[] | Prisma.CheckpointUncheckedCreateWithoutRoadmapInput[]
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutRoadmapInput | Prisma.CheckpointCreateOrConnectWithoutRoadmapInput[]
  createMany?: Prisma.CheckpointCreateManyRoadmapInputEnvelope
  connect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
}

export type CheckpointUpdateManyWithoutRoadmapNestedInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutRoadmapInput, Prisma.CheckpointUncheckedCreateWithoutRoadmapInput> | Prisma.CheckpointCreateWithoutRoadmapInput[] | Prisma.CheckpointUncheckedCreateWithoutRoadmapInput[]
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutRoadmapInput | Prisma.CheckpointCreateOrConnectWithoutRoadmapInput[]
  upsert?: Prisma.CheckpointUpsertWithWhereUniqueWithoutRoadmapInput | Prisma.CheckpointUpsertWithWhereUniqueWithoutRoadmapInput[]
  createMany?: Prisma.CheckpointCreateManyRoadmapInputEnvelope
  set?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  disconnect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  delete?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  connect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  update?: Prisma.CheckpointUpdateWithWhereUniqueWithoutRoadmapInput | Prisma.CheckpointUpdateWithWhereUniqueWithoutRoadmapInput[]
  updateMany?: Prisma.CheckpointUpdateManyWithWhereWithoutRoadmapInput | Prisma.CheckpointUpdateManyWithWhereWithoutRoadmapInput[]
  deleteMany?: Prisma.CheckpointScalarWhereInput | Prisma.CheckpointScalarWhereInput[]
}

export type CheckpointUncheckedUpdateManyWithoutRoadmapNestedInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutRoadmapInput, Prisma.CheckpointUncheckedCreateWithoutRoadmapInput> | Prisma.CheckpointCreateWithoutRoadmapInput[] | Prisma.CheckpointUncheckedCreateWithoutRoadmapInput[]
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutRoadmapInput | Prisma.CheckpointCreateOrConnectWithoutRoadmapInput[]
  upsert?: Prisma.CheckpointUpsertWithWhereUniqueWithoutRoadmapInput | Prisma.CheckpointUpsertWithWhereUniqueWithoutRoadmapInput[]
  createMany?: Prisma.CheckpointCreateManyRoadmapInputEnvelope
  set?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  disconnect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  delete?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  connect?: Prisma.CheckpointWhereUniqueInput | Prisma.CheckpointWhereUniqueInput[]
  update?: Prisma.CheckpointUpdateWithWhereUniqueWithoutRoadmapInput | Prisma.CheckpointUpdateWithWhereUniqueWithoutRoadmapInput[]
  updateMany?: Prisma.CheckpointUpdateManyWithWhereWithoutRoadmapInput | Prisma.CheckpointUpdateManyWithWhereWithoutRoadmapInput[]
  deleteMany?: Prisma.CheckpointScalarWhereInput | Prisma.CheckpointScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CheckpointCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutSessionsInput, Prisma.CheckpointUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutSessionsInput
  connect?: Prisma.CheckpointWhereUniqueInput
}

export type CheckpointUpdateOneRequiredWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.CheckpointCreateWithoutSessionsInput, Prisma.CheckpointUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.CheckpointCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.CheckpointUpsertWithoutSessionsInput
  connect?: Prisma.CheckpointWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CheckpointUpdateToOneWithWhereWithoutSessionsInput, Prisma.CheckpointUpdateWithoutSessionsInput>, Prisma.CheckpointUncheckedUpdateWithoutSessionsInput>
}

export type CheckpointCreateWithoutTagInput = {
  id?: string
  title: string
  description?: string | null
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
  roadmap: Prisma.RoadmapCreateNestedOneWithoutCheckpointsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutCheckpointInput
}

export type CheckpointUncheckedCreateWithoutTagInput = {
  id?: string
  roadmap_id: string
  title: string
  description?: string | null
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutCheckpointInput
}

export type CheckpointCreateOrConnectWithoutTagInput = {
  where: Prisma.CheckpointWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckpointCreateWithoutTagInput, Prisma.CheckpointUncheckedCreateWithoutTagInput>
}

export type CheckpointCreateManyTagInputEnvelope = {
  data: Prisma.CheckpointCreateManyTagInput | Prisma.CheckpointCreateManyTagInput[]
  skipDuplicates?: boolean
}

export type CheckpointUpsertWithWhereUniqueWithoutTagInput = {
  where: Prisma.CheckpointWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckpointUpdateWithoutTagInput, Prisma.CheckpointUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.CheckpointCreateWithoutTagInput, Prisma.CheckpointUncheckedCreateWithoutTagInput>
}

export type CheckpointUpdateWithWhereUniqueWithoutTagInput = {
  where: Prisma.CheckpointWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckpointUpdateWithoutTagInput, Prisma.CheckpointUncheckedUpdateWithoutTagInput>
}

export type CheckpointUpdateManyWithWhereWithoutTagInput = {
  where: Prisma.CheckpointScalarWhereInput
  data: Prisma.XOR<Prisma.CheckpointUpdateManyMutationInput, Prisma.CheckpointUncheckedUpdateManyWithoutTagInput>
}

export type CheckpointScalarWhereInput = {
  AND?: Prisma.CheckpointScalarWhereInput | Prisma.CheckpointScalarWhereInput[]
  OR?: Prisma.CheckpointScalarWhereInput[]
  NOT?: Prisma.CheckpointScalarWhereInput | Prisma.CheckpointScalarWhereInput[]
  id?: Prisma.UuidFilter<"Checkpoint"> | string
  roadmap_id?: Prisma.UuidFilter<"Checkpoint"> | string
  title?: Prisma.StringFilter<"Checkpoint"> | string
  description?: Prisma.StringNullableFilter<"Checkpoint"> | string | null
  tag_id?: Prisma.UuidFilter<"Checkpoint"> | string
  difficulty?: Prisma.IntFilter<"Checkpoint"> | number
  order?: Prisma.IntFilter<"Checkpoint"> | number
  status?: Prisma.StringFilter<"Checkpoint"> | string
  best_score?: Prisma.FloatNullableFilter<"Checkpoint"> | number | null
  attempts?: Prisma.IntFilter<"Checkpoint"> | number
}

export type CheckpointCreateWithoutRoadmapInput = {
  id?: string
  title: string
  description?: string | null
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
  tag: Prisma.TagCreateNestedOneWithoutCheckpointsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutCheckpointInput
}

export type CheckpointUncheckedCreateWithoutRoadmapInput = {
  id?: string
  title: string
  description?: string | null
  tag_id: string
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutCheckpointInput
}

export type CheckpointCreateOrConnectWithoutRoadmapInput = {
  where: Prisma.CheckpointWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckpointCreateWithoutRoadmapInput, Prisma.CheckpointUncheckedCreateWithoutRoadmapInput>
}

export type CheckpointCreateManyRoadmapInputEnvelope = {
  data: Prisma.CheckpointCreateManyRoadmapInput | Prisma.CheckpointCreateManyRoadmapInput[]
  skipDuplicates?: boolean
}

export type CheckpointUpsertWithWhereUniqueWithoutRoadmapInput = {
  where: Prisma.CheckpointWhereUniqueInput
  update: Prisma.XOR<Prisma.CheckpointUpdateWithoutRoadmapInput, Prisma.CheckpointUncheckedUpdateWithoutRoadmapInput>
  create: Prisma.XOR<Prisma.CheckpointCreateWithoutRoadmapInput, Prisma.CheckpointUncheckedCreateWithoutRoadmapInput>
}

export type CheckpointUpdateWithWhereUniqueWithoutRoadmapInput = {
  where: Prisma.CheckpointWhereUniqueInput
  data: Prisma.XOR<Prisma.CheckpointUpdateWithoutRoadmapInput, Prisma.CheckpointUncheckedUpdateWithoutRoadmapInput>
}

export type CheckpointUpdateManyWithWhereWithoutRoadmapInput = {
  where: Prisma.CheckpointScalarWhereInput
  data: Prisma.XOR<Prisma.CheckpointUpdateManyMutationInput, Prisma.CheckpointUncheckedUpdateManyWithoutRoadmapInput>
}

export type CheckpointCreateWithoutSessionsInput = {
  id?: string
  title: string
  description?: string | null
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
  roadmap: Prisma.RoadmapCreateNestedOneWithoutCheckpointsInput
  tag: Prisma.TagCreateNestedOneWithoutCheckpointsInput
}

export type CheckpointUncheckedCreateWithoutSessionsInput = {
  id?: string
  roadmap_id: string
  title: string
  description?: string | null
  tag_id: string
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
}

export type CheckpointCreateOrConnectWithoutSessionsInput = {
  where: Prisma.CheckpointWhereUniqueInput
  create: Prisma.XOR<Prisma.CheckpointCreateWithoutSessionsInput, Prisma.CheckpointUncheckedCreateWithoutSessionsInput>
}

export type CheckpointUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.CheckpointUpdateWithoutSessionsInput, Prisma.CheckpointUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.CheckpointCreateWithoutSessionsInput, Prisma.CheckpointUncheckedCreateWithoutSessionsInput>
  where?: Prisma.CheckpointWhereInput
}

export type CheckpointUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.CheckpointWhereInput
  data: Prisma.XOR<Prisma.CheckpointUpdateWithoutSessionsInput, Prisma.CheckpointUncheckedUpdateWithoutSessionsInput>
}

export type CheckpointUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  roadmap?: Prisma.RoadmapUpdateOneRequiredWithoutCheckpointsNestedInput
  tag?: Prisma.TagUpdateOneRequiredWithoutCheckpointsNestedInput
}

export type CheckpointUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roadmap_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tag_id?: Prisma.StringFieldUpdateOperationsInput | string
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CheckpointCreateManyTagInput = {
  id?: string
  roadmap_id: string
  title: string
  description?: string | null
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
}

export type CheckpointUpdateWithoutTagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  roadmap?: Prisma.RoadmapUpdateOneRequiredWithoutCheckpointsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutCheckpointNestedInput
}

export type CheckpointUncheckedUpdateWithoutTagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roadmap_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutCheckpointNestedInput
}

export type CheckpointUncheckedUpdateManyWithoutTagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  roadmap_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CheckpointCreateManyRoadmapInput = {
  id?: string
  title: string
  description?: string | null
  tag_id: string
  difficulty: number
  order: number
  status?: string
  best_score?: number | null
  attempts?: number
}

export type CheckpointUpdateWithoutRoadmapInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  tag?: Prisma.TagUpdateOneRequiredWithoutCheckpointsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutCheckpointNestedInput
}

export type CheckpointUncheckedUpdateWithoutRoadmapInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tag_id?: Prisma.StringFieldUpdateOperationsInput | string
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutCheckpointNestedInput
}

export type CheckpointUncheckedUpdateManyWithoutRoadmapInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tag_id?: Prisma.StringFieldUpdateOperationsInput | string
  difficulty?: Prisma.IntFieldUpdateOperationsInput | number
  order?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.StringFieldUpdateOperationsInput | string
  best_score?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  attempts?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type CheckpointCountOutputType
 */

export type CheckpointCountOutputType = {
  sessions: number
}

export type CheckpointCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessions?: boolean | CheckpointCountOutputTypeCountSessionsArgs
}

/**
 * CheckpointCountOutputType without action
 */
export type CheckpointCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CheckpointCountOutputType
   */
  select?: Prisma.CheckpointCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CheckpointCountOutputType without action
 */
export type CheckpointCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
}


export type CheckpointSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  roadmap_id?: boolean
  title?: boolean
  description?: boolean
  tag_id?: boolean
  difficulty?: boolean
  order?: boolean
  status?: boolean
  best_score?: boolean
  attempts?: boolean
  roadmap?: boolean | Prisma.RoadmapDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.Checkpoint$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.CheckpointCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checkpoint"]>

export type CheckpointSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  roadmap_id?: boolean
  title?: boolean
  description?: boolean
  tag_id?: boolean
  difficulty?: boolean
  order?: boolean
  status?: boolean
  best_score?: boolean
  attempts?: boolean
  roadmap?: boolean | Prisma.RoadmapDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checkpoint"]>

export type CheckpointSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  roadmap_id?: boolean
  title?: boolean
  description?: boolean
  tag_id?: boolean
  difficulty?: boolean
  order?: boolean
  status?: boolean
  best_score?: boolean
  attempts?: boolean
  roadmap?: boolean | Prisma.RoadmapDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["checkpoint"]>

export type CheckpointSelectScalar = {
  id?: boolean
  roadmap_id?: boolean
  title?: boolean
  description?: boolean
  tag_id?: boolean
  difficulty?: boolean
  order?: boolean
  status?: boolean
  best_score?: boolean
  attempts?: boolean
}

export type CheckpointOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "roadmap_id" | "title" | "description" | "tag_id" | "difficulty" | "order" | "status" | "best_score" | "attempts", ExtArgs["result"]["checkpoint"]>
export type CheckpointInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roadmap?: boolean | Prisma.RoadmapDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.Checkpoint$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.CheckpointCountOutputTypeDefaultArgs<ExtArgs>
}
export type CheckpointIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roadmap?: boolean | Prisma.RoadmapDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}
export type CheckpointIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  roadmap?: boolean | Prisma.RoadmapDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}

export type $CheckpointPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Checkpoint"
  objects: {
    roadmap: Prisma.$RoadmapPayload<ExtArgs>
    tag: Prisma.$TagPayload<ExtArgs>
    sessions: Prisma.$SessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    roadmap_id: string
    title: string
    description: string | null
    tag_id: string
    difficulty: number
    order: number
    status: string
    best_score: number | null
    attempts: number
  }, ExtArgs["result"]["checkpoint"]>
  composites: {}
}

export type CheckpointGetPayload<S extends boolean | null | undefined | CheckpointDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CheckpointPayload, S>

export type CheckpointCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CheckpointFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CheckpointCountAggregateInputType | true
  }

export interface CheckpointDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Checkpoint'], meta: { name: 'Checkpoint' } }
  /**
   * Find zero or one Checkpoint that matches the filter.
   * @param {CheckpointFindUniqueArgs} args - Arguments to find a Checkpoint
   * @example
   * // Get one Checkpoint
   * const checkpoint = await prisma.checkpoint.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CheckpointFindUniqueArgs>(args: Prisma.SelectSubset<T, CheckpointFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CheckpointClient<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Checkpoint that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CheckpointFindUniqueOrThrowArgs} args - Arguments to find a Checkpoint
   * @example
   * // Get one Checkpoint
   * const checkpoint = await prisma.checkpoint.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CheckpointFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CheckpointFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckpointClient<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Checkpoint that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckpointFindFirstArgs} args - Arguments to find a Checkpoint
   * @example
   * // Get one Checkpoint
   * const checkpoint = await prisma.checkpoint.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CheckpointFindFirstArgs>(args?: Prisma.SelectSubset<T, CheckpointFindFirstArgs<ExtArgs>>): Prisma.Prisma__CheckpointClient<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Checkpoint that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckpointFindFirstOrThrowArgs} args - Arguments to find a Checkpoint
   * @example
   * // Get one Checkpoint
   * const checkpoint = await prisma.checkpoint.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CheckpointFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CheckpointFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CheckpointClient<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Checkpoints that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckpointFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Checkpoints
   * const checkpoints = await prisma.checkpoint.findMany()
   * 
   * // Get first 10 Checkpoints
   * const checkpoints = await prisma.checkpoint.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const checkpointWithIdOnly = await prisma.checkpoint.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CheckpointFindManyArgs>(args?: Prisma.SelectSubset<T, CheckpointFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Checkpoint.
   * @param {CheckpointCreateArgs} args - Arguments to create a Checkpoint.
   * @example
   * // Create one Checkpoint
   * const Checkpoint = await prisma.checkpoint.create({
   *   data: {
   *     // ... data to create a Checkpoint
   *   }
   * })
   * 
   */
  create<T extends CheckpointCreateArgs>(args: Prisma.SelectSubset<T, CheckpointCreateArgs<ExtArgs>>): Prisma.Prisma__CheckpointClient<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Checkpoints.
   * @param {CheckpointCreateManyArgs} args - Arguments to create many Checkpoints.
   * @example
   * // Create many Checkpoints
   * const checkpoint = await prisma.checkpoint.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CheckpointCreateManyArgs>(args?: Prisma.SelectSubset<T, CheckpointCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Checkpoints and returns the data saved in the database.
   * @param {CheckpointCreateManyAndReturnArgs} args - Arguments to create many Checkpoints.
   * @example
   * // Create many Checkpoints
   * const checkpoint = await prisma.checkpoint.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Checkpoints and only return the `id`
   * const checkpointWithIdOnly = await prisma.checkpoint.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CheckpointCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CheckpointCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Checkpoint.
   * @param {CheckpointDeleteArgs} args - Arguments to delete one Checkpoint.
   * @example
   * // Delete one Checkpoint
   * const Checkpoint = await prisma.checkpoint.delete({
   *   where: {
   *     // ... filter to delete one Checkpoint
   *   }
   * })
   * 
   */
  delete<T extends CheckpointDeleteArgs>(args: Prisma.SelectSubset<T, CheckpointDeleteArgs<ExtArgs>>): Prisma.Prisma__CheckpointClient<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Checkpoint.
   * @param {CheckpointUpdateArgs} args - Arguments to update one Checkpoint.
   * @example
   * // Update one Checkpoint
   * const checkpoint = await prisma.checkpoint.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CheckpointUpdateArgs>(args: Prisma.SelectSubset<T, CheckpointUpdateArgs<ExtArgs>>): Prisma.Prisma__CheckpointClient<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Checkpoints.
   * @param {CheckpointDeleteManyArgs} args - Arguments to filter Checkpoints to delete.
   * @example
   * // Delete a few Checkpoints
   * const { count } = await prisma.checkpoint.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CheckpointDeleteManyArgs>(args?: Prisma.SelectSubset<T, CheckpointDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Checkpoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckpointUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Checkpoints
   * const checkpoint = await prisma.checkpoint.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CheckpointUpdateManyArgs>(args: Prisma.SelectSubset<T, CheckpointUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Checkpoints and returns the data updated in the database.
   * @param {CheckpointUpdateManyAndReturnArgs} args - Arguments to update many Checkpoints.
   * @example
   * // Update many Checkpoints
   * const checkpoint = await prisma.checkpoint.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Checkpoints and only return the `id`
   * const checkpointWithIdOnly = await prisma.checkpoint.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CheckpointUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CheckpointUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Checkpoint.
   * @param {CheckpointUpsertArgs} args - Arguments to update or create a Checkpoint.
   * @example
   * // Update or create a Checkpoint
   * const checkpoint = await prisma.checkpoint.upsert({
   *   create: {
   *     // ... data to create a Checkpoint
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Checkpoint we want to update
   *   }
   * })
   */
  upsert<T extends CheckpointUpsertArgs>(args: Prisma.SelectSubset<T, CheckpointUpsertArgs<ExtArgs>>): Prisma.Prisma__CheckpointClient<runtime.Types.Result.GetResult<Prisma.$CheckpointPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Checkpoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckpointCountArgs} args - Arguments to filter Checkpoints to count.
   * @example
   * // Count the number of Checkpoints
   * const count = await prisma.checkpoint.count({
   *   where: {
   *     // ... the filter for the Checkpoints we want to count
   *   }
   * })
  **/
  count<T extends CheckpointCountArgs>(
    args?: Prisma.Subset<T, CheckpointCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CheckpointCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Checkpoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckpointAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CheckpointAggregateArgs>(args: Prisma.Subset<T, CheckpointAggregateArgs>): Prisma.PrismaPromise<GetCheckpointAggregateType<T>>

  /**
   * Group by Checkpoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CheckpointGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CheckpointGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CheckpointGroupByArgs['orderBy'] }
      : { orderBy?: CheckpointGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CheckpointGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCheckpointGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Checkpoint model
 */
readonly fields: CheckpointFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Checkpoint.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CheckpointClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  roadmap<T extends Prisma.RoadmapDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RoadmapDefaultArgs<ExtArgs>>): Prisma.Prisma__RoadmapClient<runtime.Types.Result.GetResult<Prisma.$RoadmapPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tag<T extends Prisma.TagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagDefaultArgs<ExtArgs>>): Prisma.Prisma__TagClient<runtime.Types.Result.GetResult<Prisma.$TagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sessions<T extends Prisma.Checkpoint$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Checkpoint$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Checkpoint model
 */
export interface CheckpointFieldRefs {
  readonly id: Prisma.FieldRef<"Checkpoint", 'String'>
  readonly roadmap_id: Prisma.FieldRef<"Checkpoint", 'String'>
  readonly title: Prisma.FieldRef<"Checkpoint", 'String'>
  readonly description: Prisma.FieldRef<"Checkpoint", 'String'>
  readonly tag_id: Prisma.FieldRef<"Checkpoint", 'String'>
  readonly difficulty: Prisma.FieldRef<"Checkpoint", 'Int'>
  readonly order: Prisma.FieldRef<"Checkpoint", 'Int'>
  readonly status: Prisma.FieldRef<"Checkpoint", 'String'>
  readonly best_score: Prisma.FieldRef<"Checkpoint", 'Float'>
  readonly attempts: Prisma.FieldRef<"Checkpoint", 'Int'>
}
    

// Custom InputTypes
/**
 * Checkpoint findUnique
 */
export type CheckpointFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
  /**
   * Filter, which Checkpoint to fetch.
   */
  where: Prisma.CheckpointWhereUniqueInput
}

/**
 * Checkpoint findUniqueOrThrow
 */
export type CheckpointFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
  /**
   * Filter, which Checkpoint to fetch.
   */
  where: Prisma.CheckpointWhereUniqueInput
}

/**
 * Checkpoint findFirst
 */
export type CheckpointFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
  /**
   * Filter, which Checkpoint to fetch.
   */
  where?: Prisma.CheckpointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checkpoints to fetch.
   */
  orderBy?: Prisma.CheckpointOrderByWithRelationInput | Prisma.CheckpointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Checkpoints.
   */
  cursor?: Prisma.CheckpointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checkpoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checkpoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Checkpoints.
   */
  distinct?: Prisma.CheckpointScalarFieldEnum | Prisma.CheckpointScalarFieldEnum[]
}

/**
 * Checkpoint findFirstOrThrow
 */
export type CheckpointFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
  /**
   * Filter, which Checkpoint to fetch.
   */
  where?: Prisma.CheckpointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checkpoints to fetch.
   */
  orderBy?: Prisma.CheckpointOrderByWithRelationInput | Prisma.CheckpointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Checkpoints.
   */
  cursor?: Prisma.CheckpointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checkpoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checkpoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Checkpoints.
   */
  distinct?: Prisma.CheckpointScalarFieldEnum | Prisma.CheckpointScalarFieldEnum[]
}

/**
 * Checkpoint findMany
 */
export type CheckpointFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
  /**
   * Filter, which Checkpoints to fetch.
   */
  where?: Prisma.CheckpointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Checkpoints to fetch.
   */
  orderBy?: Prisma.CheckpointOrderByWithRelationInput | Prisma.CheckpointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Checkpoints.
   */
  cursor?: Prisma.CheckpointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Checkpoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Checkpoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Checkpoints.
   */
  distinct?: Prisma.CheckpointScalarFieldEnum | Prisma.CheckpointScalarFieldEnum[]
}

/**
 * Checkpoint create
 */
export type CheckpointCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
  /**
   * The data needed to create a Checkpoint.
   */
  data: Prisma.XOR<Prisma.CheckpointCreateInput, Prisma.CheckpointUncheckedCreateInput>
}

/**
 * Checkpoint createMany
 */
export type CheckpointCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Checkpoints.
   */
  data: Prisma.CheckpointCreateManyInput | Prisma.CheckpointCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Checkpoint createManyAndReturn
 */
export type CheckpointCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * The data used to create many Checkpoints.
   */
  data: Prisma.CheckpointCreateManyInput | Prisma.CheckpointCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Checkpoint update
 */
export type CheckpointUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
  /**
   * The data needed to update a Checkpoint.
   */
  data: Prisma.XOR<Prisma.CheckpointUpdateInput, Prisma.CheckpointUncheckedUpdateInput>
  /**
   * Choose, which Checkpoint to update.
   */
  where: Prisma.CheckpointWhereUniqueInput
}

/**
 * Checkpoint updateMany
 */
export type CheckpointUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Checkpoints.
   */
  data: Prisma.XOR<Prisma.CheckpointUpdateManyMutationInput, Prisma.CheckpointUncheckedUpdateManyInput>
  /**
   * Filter which Checkpoints to update
   */
  where?: Prisma.CheckpointWhereInput
  /**
   * Limit how many Checkpoints to update.
   */
  limit?: number
}

/**
 * Checkpoint updateManyAndReturn
 */
export type CheckpointUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * The data used to update Checkpoints.
   */
  data: Prisma.XOR<Prisma.CheckpointUpdateManyMutationInput, Prisma.CheckpointUncheckedUpdateManyInput>
  /**
   * Filter which Checkpoints to update
   */
  where?: Prisma.CheckpointWhereInput
  /**
   * Limit how many Checkpoints to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Checkpoint upsert
 */
export type CheckpointUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
  /**
   * The filter to search for the Checkpoint to update in case it exists.
   */
  where: Prisma.CheckpointWhereUniqueInput
  /**
   * In case the Checkpoint found by the `where` argument doesn't exist, create a new Checkpoint with this data.
   */
  create: Prisma.XOR<Prisma.CheckpointCreateInput, Prisma.CheckpointUncheckedCreateInput>
  /**
   * In case the Checkpoint was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CheckpointUpdateInput, Prisma.CheckpointUncheckedUpdateInput>
}

/**
 * Checkpoint delete
 */
export type CheckpointDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
  /**
   * Filter which Checkpoint to delete.
   */
  where: Prisma.CheckpointWhereUniqueInput
}

/**
 * Checkpoint deleteMany
 */
export type CheckpointDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Checkpoints to delete
   */
  where?: Prisma.CheckpointWhereInput
  /**
   * Limit how many Checkpoints to delete.
   */
  limit?: number
}

/**
 * Checkpoint.sessions
 */
export type Checkpoint$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  cursor?: Prisma.SessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * Checkpoint without action
 */
export type CheckpointDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Checkpoint
   */
  select?: Prisma.CheckpointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Checkpoint
   */
  omit?: Prisma.CheckpointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CheckpointInclude<ExtArgs> | null
}
