
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DomainEmbedding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DomainEmbedding
 * 
 */
export type DomainEmbeddingModel = runtime.Types.Result.DefaultSelection<Prisma.$DomainEmbeddingPayload>

export type AggregateDomainEmbedding = {
  _count: DomainEmbeddingCountAggregateOutputType | null
  _min: DomainEmbeddingMinAggregateOutputType | null
  _max: DomainEmbeddingMaxAggregateOutputType | null
}

export type DomainEmbeddingMinAggregateOutputType = {
  id: string | null
  domain_id: string | null
  created_at: Date | null
}

export type DomainEmbeddingMaxAggregateOutputType = {
  id: string | null
  domain_id: string | null
  created_at: Date | null
}

export type DomainEmbeddingCountAggregateOutputType = {
  id: number
  domain_id: number
  created_at: number
  _all: number
}


export type DomainEmbeddingMinAggregateInputType = {
  id?: true
  domain_id?: true
  created_at?: true
}

export type DomainEmbeddingMaxAggregateInputType = {
  id?: true
  domain_id?: true
  created_at?: true
}

export type DomainEmbeddingCountAggregateInputType = {
  id?: true
  domain_id?: true
  created_at?: true
  _all?: true
}

export type DomainEmbeddingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DomainEmbedding to aggregate.
   */
  where?: Prisma.DomainEmbeddingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DomainEmbeddings to fetch.
   */
  orderBy?: Prisma.DomainEmbeddingOrderByWithRelationInput | Prisma.DomainEmbeddingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DomainEmbeddingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DomainEmbeddings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DomainEmbeddings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DomainEmbeddings
  **/
  _count?: true | DomainEmbeddingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DomainEmbeddingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DomainEmbeddingMaxAggregateInputType
}

export type GetDomainEmbeddingAggregateType<T extends DomainEmbeddingAggregateArgs> = {
      [P in keyof T & keyof AggregateDomainEmbedding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDomainEmbedding[P]>
    : Prisma.GetScalarType<T[P], AggregateDomainEmbedding[P]>
}




export type DomainEmbeddingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DomainEmbeddingWhereInput
  orderBy?: Prisma.DomainEmbeddingOrderByWithAggregationInput | Prisma.DomainEmbeddingOrderByWithAggregationInput[]
  by: Prisma.DomainEmbeddingScalarFieldEnum[] | Prisma.DomainEmbeddingScalarFieldEnum
  having?: Prisma.DomainEmbeddingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DomainEmbeddingCountAggregateInputType | true
  _min?: DomainEmbeddingMinAggregateInputType
  _max?: DomainEmbeddingMaxAggregateInputType
}

export type DomainEmbeddingGroupByOutputType = {
  id: string
  domain_id: string
  created_at: Date
  _count: DomainEmbeddingCountAggregateOutputType | null
  _min: DomainEmbeddingMinAggregateOutputType | null
  _max: DomainEmbeddingMaxAggregateOutputType | null
}

export type GetDomainEmbeddingGroupByPayload<T extends DomainEmbeddingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DomainEmbeddingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DomainEmbeddingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DomainEmbeddingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DomainEmbeddingGroupByOutputType[P]>
      }
    >
  >



export type DomainEmbeddingWhereInput = {
  AND?: Prisma.DomainEmbeddingWhereInput | Prisma.DomainEmbeddingWhereInput[]
  OR?: Prisma.DomainEmbeddingWhereInput[]
  NOT?: Prisma.DomainEmbeddingWhereInput | Prisma.DomainEmbeddingWhereInput[]
  id?: Prisma.UuidFilter<"DomainEmbedding"> | string
  domain_id?: Prisma.UuidFilter<"DomainEmbedding"> | string
  created_at?: Prisma.DateTimeFilter<"DomainEmbedding"> | Date | string
  domain?: Prisma.XOR<Prisma.DomainScalarRelationFilter, Prisma.DomainWhereInput>
}

export type DomainEmbeddingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  domain_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  domain?: Prisma.DomainOrderByWithRelationInput
}

export type DomainEmbeddingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  domain_id?: string
  AND?: Prisma.DomainEmbeddingWhereInput | Prisma.DomainEmbeddingWhereInput[]
  OR?: Prisma.DomainEmbeddingWhereInput[]
  NOT?: Prisma.DomainEmbeddingWhereInput | Prisma.DomainEmbeddingWhereInput[]
  created_at?: Prisma.DateTimeFilter<"DomainEmbedding"> | Date | string
  domain?: Prisma.XOR<Prisma.DomainScalarRelationFilter, Prisma.DomainWhereInput>
}, "id" | "domain_id">

export type DomainEmbeddingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  domain_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.DomainEmbeddingCountOrderByAggregateInput
  _max?: Prisma.DomainEmbeddingMaxOrderByAggregateInput
  _min?: Prisma.DomainEmbeddingMinOrderByAggregateInput
}

export type DomainEmbeddingScalarWhereWithAggregatesInput = {
  AND?: Prisma.DomainEmbeddingScalarWhereWithAggregatesInput | Prisma.DomainEmbeddingScalarWhereWithAggregatesInput[]
  OR?: Prisma.DomainEmbeddingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DomainEmbeddingScalarWhereWithAggregatesInput | Prisma.DomainEmbeddingScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"DomainEmbedding"> | string
  domain_id?: Prisma.UuidWithAggregatesFilter<"DomainEmbedding"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"DomainEmbedding"> | Date | string
}

export type DomainEmbeddingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  domain?: Prisma.DomainUpdateOneRequiredWithoutEmbeddingNestedInput
}

export type DomainEmbeddingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DomainEmbeddingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DomainEmbeddingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  domain_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DomainEmbeddingNullableScalarRelationFilter = {
  is?: Prisma.DomainEmbeddingWhereInput | null
  isNot?: Prisma.DomainEmbeddingWhereInput | null
}

export type DomainEmbeddingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  domain_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type DomainEmbeddingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  domain_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type DomainEmbeddingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  domain_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type DomainEmbeddingCreateNestedOneWithoutDomainInput = {
  connect?: Prisma.DomainEmbeddingWhereUniqueInput
}

export type DomainEmbeddingUncheckedCreateNestedOneWithoutDomainInput = {
  connect?: Prisma.DomainEmbeddingWhereUniqueInput
}

export type DomainEmbeddingUpdateOneWithoutDomainNestedInput = {
  disconnect?: Prisma.DomainEmbeddingWhereInput | boolean
  delete?: Prisma.DomainEmbeddingWhereInput | boolean
  connect?: Prisma.DomainEmbeddingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DomainEmbeddingUpdateToOneWithWhereWithoutDomainInput, Prisma.DomainEmbeddingUpdateWithoutDomainInput>, Prisma.DomainEmbeddingUncheckedUpdateWithoutDomainInput>
}

export type DomainEmbeddingUncheckedUpdateOneWithoutDomainNestedInput = {
  disconnect?: Prisma.DomainEmbeddingWhereInput | boolean
  delete?: Prisma.DomainEmbeddingWhereInput | boolean
  connect?: Prisma.DomainEmbeddingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DomainEmbeddingUpdateToOneWithWhereWithoutDomainInput, Prisma.DomainEmbeddingUpdateWithoutDomainInput>, Prisma.DomainEmbeddingUncheckedUpdateWithoutDomainInput>
}

export type DomainEmbeddingUpdateToOneWithWhereWithoutDomainInput = {
  where?: Prisma.DomainEmbeddingWhereInput
  data: Prisma.XOR<Prisma.DomainEmbeddingUpdateWithoutDomainInput, Prisma.DomainEmbeddingUncheckedUpdateWithoutDomainInput>
}

export type DomainEmbeddingUpdateWithoutDomainInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DomainEmbeddingUncheckedUpdateWithoutDomainInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type DomainEmbeddingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  domain_id?: boolean
  created_at?: boolean
  domain?: boolean | Prisma.DomainDefaultArgs<ExtArgs>
}, ExtArgs["result"]["domainEmbedding"]>


export type DomainEmbeddingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  domain_id?: boolean
  created_at?: boolean
  domain?: boolean | Prisma.DomainDefaultArgs<ExtArgs>
}, ExtArgs["result"]["domainEmbedding"]>

export type DomainEmbeddingSelectScalar = {
  id?: boolean
  domain_id?: boolean
  created_at?: boolean
}

export type DomainEmbeddingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "domain_id" | "created_at", ExtArgs["result"]["domainEmbedding"]>
export type DomainEmbeddingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  domain?: boolean | Prisma.DomainDefaultArgs<ExtArgs>
}
export type DomainEmbeddingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  domain?: boolean | Prisma.DomainDefaultArgs<ExtArgs>
}

export type $DomainEmbeddingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DomainEmbedding"
  objects: {
    domain: Prisma.$DomainPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    domain_id: string
    created_at: Date
  }, ExtArgs["result"]["domainEmbedding"]>
  composites: {}
}

export type DomainEmbeddingGetPayload<S extends boolean | null | undefined | DomainEmbeddingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DomainEmbeddingPayload, S>

export type DomainEmbeddingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DomainEmbeddingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DomainEmbeddingCountAggregateInputType | true
  }

export interface DomainEmbeddingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DomainEmbedding'], meta: { name: 'DomainEmbedding' } }
  /**
   * Find zero or one DomainEmbedding that matches the filter.
   * @param {DomainEmbeddingFindUniqueArgs} args - Arguments to find a DomainEmbedding
   * @example
   * // Get one DomainEmbedding
   * const domainEmbedding = await prisma.domainEmbedding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DomainEmbeddingFindUniqueArgs>(args: Prisma.SelectSubset<T, DomainEmbeddingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DomainEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$DomainEmbeddingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DomainEmbedding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DomainEmbeddingFindUniqueOrThrowArgs} args - Arguments to find a DomainEmbedding
   * @example
   * // Get one DomainEmbedding
   * const domainEmbedding = await prisma.domainEmbedding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DomainEmbeddingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DomainEmbeddingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DomainEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$DomainEmbeddingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DomainEmbedding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DomainEmbeddingFindFirstArgs} args - Arguments to find a DomainEmbedding
   * @example
   * // Get one DomainEmbedding
   * const domainEmbedding = await prisma.domainEmbedding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DomainEmbeddingFindFirstArgs>(args?: Prisma.SelectSubset<T, DomainEmbeddingFindFirstArgs<ExtArgs>>): Prisma.Prisma__DomainEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$DomainEmbeddingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DomainEmbedding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DomainEmbeddingFindFirstOrThrowArgs} args - Arguments to find a DomainEmbedding
   * @example
   * // Get one DomainEmbedding
   * const domainEmbedding = await prisma.domainEmbedding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DomainEmbeddingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DomainEmbeddingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DomainEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$DomainEmbeddingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DomainEmbeddings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DomainEmbeddingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DomainEmbeddings
   * const domainEmbeddings = await prisma.domainEmbedding.findMany()
   * 
   * // Get first 10 DomainEmbeddings
   * const domainEmbeddings = await prisma.domainEmbedding.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const domainEmbeddingWithIdOnly = await prisma.domainEmbedding.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DomainEmbeddingFindManyArgs>(args?: Prisma.SelectSubset<T, DomainEmbeddingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DomainEmbeddingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Delete a DomainEmbedding.
   * @param {DomainEmbeddingDeleteArgs} args - Arguments to delete one DomainEmbedding.
   * @example
   * // Delete one DomainEmbedding
   * const DomainEmbedding = await prisma.domainEmbedding.delete({
   *   where: {
   *     // ... filter to delete one DomainEmbedding
   *   }
   * })
   * 
   */
  delete<T extends DomainEmbeddingDeleteArgs>(args: Prisma.SelectSubset<T, DomainEmbeddingDeleteArgs<ExtArgs>>): Prisma.Prisma__DomainEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$DomainEmbeddingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DomainEmbedding.
   * @param {DomainEmbeddingUpdateArgs} args - Arguments to update one DomainEmbedding.
   * @example
   * // Update one DomainEmbedding
   * const domainEmbedding = await prisma.domainEmbedding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DomainEmbeddingUpdateArgs>(args: Prisma.SelectSubset<T, DomainEmbeddingUpdateArgs<ExtArgs>>): Prisma.Prisma__DomainEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$DomainEmbeddingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DomainEmbeddings.
   * @param {DomainEmbeddingDeleteManyArgs} args - Arguments to filter DomainEmbeddings to delete.
   * @example
   * // Delete a few DomainEmbeddings
   * const { count } = await prisma.domainEmbedding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DomainEmbeddingDeleteManyArgs>(args?: Prisma.SelectSubset<T, DomainEmbeddingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DomainEmbeddings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DomainEmbeddingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DomainEmbeddings
   * const domainEmbedding = await prisma.domainEmbedding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DomainEmbeddingUpdateManyArgs>(args: Prisma.SelectSubset<T, DomainEmbeddingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DomainEmbeddings and returns the data updated in the database.
   * @param {DomainEmbeddingUpdateManyAndReturnArgs} args - Arguments to update many DomainEmbeddings.
   * @example
   * // Update many DomainEmbeddings
   * const domainEmbedding = await prisma.domainEmbedding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DomainEmbeddings and only return the `id`
   * const domainEmbeddingWithIdOnly = await prisma.domainEmbedding.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DomainEmbeddingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DomainEmbeddingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DomainEmbeddingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>


  /**
   * Count the number of DomainEmbeddings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DomainEmbeddingCountArgs} args - Arguments to filter DomainEmbeddings to count.
   * @example
   * // Count the number of DomainEmbeddings
   * const count = await prisma.domainEmbedding.count({
   *   where: {
   *     // ... the filter for the DomainEmbeddings we want to count
   *   }
   * })
  **/
  count<T extends DomainEmbeddingCountArgs>(
    args?: Prisma.Subset<T, DomainEmbeddingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DomainEmbeddingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DomainEmbedding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DomainEmbeddingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DomainEmbeddingAggregateArgs>(args: Prisma.Subset<T, DomainEmbeddingAggregateArgs>): Prisma.PrismaPromise<GetDomainEmbeddingAggregateType<T>>

  /**
   * Group by DomainEmbedding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DomainEmbeddingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DomainEmbeddingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DomainEmbeddingGroupByArgs['orderBy'] }
      : { orderBy?: DomainEmbeddingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DomainEmbeddingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDomainEmbeddingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DomainEmbedding model
 */
readonly fields: DomainEmbeddingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DomainEmbedding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DomainEmbeddingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  domain<T extends Prisma.DomainDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DomainDefaultArgs<ExtArgs>>): Prisma.Prisma__DomainClient<runtime.Types.Result.GetResult<Prisma.$DomainPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DomainEmbedding model
 */
export interface DomainEmbeddingFieldRefs {
  readonly id: Prisma.FieldRef<"DomainEmbedding", 'String'>
  readonly domain_id: Prisma.FieldRef<"DomainEmbedding", 'String'>
  readonly created_at: Prisma.FieldRef<"DomainEmbedding", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DomainEmbedding findUnique
 */
export type DomainEmbeddingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DomainEmbedding
   */
  select?: Prisma.DomainEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DomainEmbedding
   */
  omit?: Prisma.DomainEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DomainEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which DomainEmbedding to fetch.
   */
  where: Prisma.DomainEmbeddingWhereUniqueInput
}

/**
 * DomainEmbedding findUniqueOrThrow
 */
export type DomainEmbeddingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DomainEmbedding
   */
  select?: Prisma.DomainEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DomainEmbedding
   */
  omit?: Prisma.DomainEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DomainEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which DomainEmbedding to fetch.
   */
  where: Prisma.DomainEmbeddingWhereUniqueInput
}

/**
 * DomainEmbedding findFirst
 */
export type DomainEmbeddingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DomainEmbedding
   */
  select?: Prisma.DomainEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DomainEmbedding
   */
  omit?: Prisma.DomainEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DomainEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which DomainEmbedding to fetch.
   */
  where?: Prisma.DomainEmbeddingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DomainEmbeddings to fetch.
   */
  orderBy?: Prisma.DomainEmbeddingOrderByWithRelationInput | Prisma.DomainEmbeddingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DomainEmbeddings.
   */
  cursor?: Prisma.DomainEmbeddingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DomainEmbeddings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DomainEmbeddings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DomainEmbeddings.
   */
  distinct?: Prisma.DomainEmbeddingScalarFieldEnum | Prisma.DomainEmbeddingScalarFieldEnum[]
}

/**
 * DomainEmbedding findFirstOrThrow
 */
export type DomainEmbeddingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DomainEmbedding
   */
  select?: Prisma.DomainEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DomainEmbedding
   */
  omit?: Prisma.DomainEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DomainEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which DomainEmbedding to fetch.
   */
  where?: Prisma.DomainEmbeddingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DomainEmbeddings to fetch.
   */
  orderBy?: Prisma.DomainEmbeddingOrderByWithRelationInput | Prisma.DomainEmbeddingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DomainEmbeddings.
   */
  cursor?: Prisma.DomainEmbeddingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DomainEmbeddings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DomainEmbeddings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DomainEmbeddings.
   */
  distinct?: Prisma.DomainEmbeddingScalarFieldEnum | Prisma.DomainEmbeddingScalarFieldEnum[]
}

/**
 * DomainEmbedding findMany
 */
export type DomainEmbeddingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DomainEmbedding
   */
  select?: Prisma.DomainEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DomainEmbedding
   */
  omit?: Prisma.DomainEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DomainEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which DomainEmbeddings to fetch.
   */
  where?: Prisma.DomainEmbeddingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DomainEmbeddings to fetch.
   */
  orderBy?: Prisma.DomainEmbeddingOrderByWithRelationInput | Prisma.DomainEmbeddingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DomainEmbeddings.
   */
  cursor?: Prisma.DomainEmbeddingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DomainEmbeddings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DomainEmbeddings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DomainEmbeddings.
   */
  distinct?: Prisma.DomainEmbeddingScalarFieldEnum | Prisma.DomainEmbeddingScalarFieldEnum[]
}

/**
 * DomainEmbedding update
 */
export type DomainEmbeddingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DomainEmbedding
   */
  select?: Prisma.DomainEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DomainEmbedding
   */
  omit?: Prisma.DomainEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DomainEmbeddingInclude<ExtArgs> | null
  /**
   * The data needed to update a DomainEmbedding.
   */
  data: Prisma.XOR<Prisma.DomainEmbeddingUpdateInput, Prisma.DomainEmbeddingUncheckedUpdateInput>
  /**
   * Choose, which DomainEmbedding to update.
   */
  where: Prisma.DomainEmbeddingWhereUniqueInput
}

/**
 * DomainEmbedding updateMany
 */
export type DomainEmbeddingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DomainEmbeddings.
   */
  data: Prisma.XOR<Prisma.DomainEmbeddingUpdateManyMutationInput, Prisma.DomainEmbeddingUncheckedUpdateManyInput>
  /**
   * Filter which DomainEmbeddings to update
   */
  where?: Prisma.DomainEmbeddingWhereInput
  /**
   * Limit how many DomainEmbeddings to update.
   */
  limit?: number
}

/**
 * DomainEmbedding updateManyAndReturn
 */
export type DomainEmbeddingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DomainEmbedding
   */
  select?: Prisma.DomainEmbeddingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DomainEmbedding
   */
  omit?: Prisma.DomainEmbeddingOmit<ExtArgs> | null
  /**
   * The data used to update DomainEmbeddings.
   */
  data: Prisma.XOR<Prisma.DomainEmbeddingUpdateManyMutationInput, Prisma.DomainEmbeddingUncheckedUpdateManyInput>
  /**
   * Filter which DomainEmbeddings to update
   */
  where?: Prisma.DomainEmbeddingWhereInput
  /**
   * Limit how many DomainEmbeddings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DomainEmbeddingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DomainEmbedding delete
 */
export type DomainEmbeddingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DomainEmbedding
   */
  select?: Prisma.DomainEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DomainEmbedding
   */
  omit?: Prisma.DomainEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DomainEmbeddingInclude<ExtArgs> | null
  /**
   * Filter which DomainEmbedding to delete.
   */
  where: Prisma.DomainEmbeddingWhereUniqueInput
}

/**
 * DomainEmbedding deleteMany
 */
export type DomainEmbeddingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DomainEmbeddings to delete
   */
  where?: Prisma.DomainEmbeddingWhereInput
  /**
   * Limit how many DomainEmbeddings to delete.
   */
  limit?: number
}

/**
 * DomainEmbedding without action
 */
export type DomainEmbeddingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DomainEmbedding
   */
  select?: Prisma.DomainEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DomainEmbedding
   */
  omit?: Prisma.DomainEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DomainEmbeddingInclude<ExtArgs> | null
}
