
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TagEmbedding` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TagEmbedding
 * 
 */
export type TagEmbeddingModel = runtime.Types.Result.DefaultSelection<Prisma.$TagEmbeddingPayload>

export type AggregateTagEmbedding = {
  _count: TagEmbeddingCountAggregateOutputType | null
  _min: TagEmbeddingMinAggregateOutputType | null
  _max: TagEmbeddingMaxAggregateOutputType | null
}

export type TagEmbeddingMinAggregateOutputType = {
  id: string | null
  tag_id: string | null
  created_at: Date | null
}

export type TagEmbeddingMaxAggregateOutputType = {
  id: string | null
  tag_id: string | null
  created_at: Date | null
}

export type TagEmbeddingCountAggregateOutputType = {
  id: number
  tag_id: number
  created_at: number
  _all: number
}


export type TagEmbeddingMinAggregateInputType = {
  id?: true
  tag_id?: true
  created_at?: true
}

export type TagEmbeddingMaxAggregateInputType = {
  id?: true
  tag_id?: true
  created_at?: true
}

export type TagEmbeddingCountAggregateInputType = {
  id?: true
  tag_id?: true
  created_at?: true
  _all?: true
}

export type TagEmbeddingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagEmbedding to aggregate.
   */
  where?: Prisma.TagEmbeddingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagEmbeddings to fetch.
   */
  orderBy?: Prisma.TagEmbeddingOrderByWithRelationInput | Prisma.TagEmbeddingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TagEmbeddingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagEmbeddings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagEmbeddings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TagEmbeddings
  **/
  _count?: true | TagEmbeddingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TagEmbeddingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TagEmbeddingMaxAggregateInputType
}

export type GetTagEmbeddingAggregateType<T extends TagEmbeddingAggregateArgs> = {
      [P in keyof T & keyof AggregateTagEmbedding]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTagEmbedding[P]>
    : Prisma.GetScalarType<T[P], AggregateTagEmbedding[P]>
}




export type TagEmbeddingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TagEmbeddingWhereInput
  orderBy?: Prisma.TagEmbeddingOrderByWithAggregationInput | Prisma.TagEmbeddingOrderByWithAggregationInput[]
  by: Prisma.TagEmbeddingScalarFieldEnum[] | Prisma.TagEmbeddingScalarFieldEnum
  having?: Prisma.TagEmbeddingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TagEmbeddingCountAggregateInputType | true
  _min?: TagEmbeddingMinAggregateInputType
  _max?: TagEmbeddingMaxAggregateInputType
}

export type TagEmbeddingGroupByOutputType = {
  id: string
  tag_id: string
  created_at: Date
  _count: TagEmbeddingCountAggregateOutputType | null
  _min: TagEmbeddingMinAggregateOutputType | null
  _max: TagEmbeddingMaxAggregateOutputType | null
}

export type GetTagEmbeddingGroupByPayload<T extends TagEmbeddingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TagEmbeddingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TagEmbeddingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TagEmbeddingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TagEmbeddingGroupByOutputType[P]>
      }
    >
  >



export type TagEmbeddingWhereInput = {
  AND?: Prisma.TagEmbeddingWhereInput | Prisma.TagEmbeddingWhereInput[]
  OR?: Prisma.TagEmbeddingWhereInput[]
  NOT?: Prisma.TagEmbeddingWhereInput | Prisma.TagEmbeddingWhereInput[]
  id?: Prisma.UuidFilter<"TagEmbedding"> | string
  tag_id?: Prisma.UuidFilter<"TagEmbedding"> | string
  created_at?: Prisma.DateTimeFilter<"TagEmbedding"> | Date | string
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}

export type TagEmbeddingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  tag?: Prisma.TagOrderByWithRelationInput
}

export type TagEmbeddingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  tag_id?: string
  AND?: Prisma.TagEmbeddingWhereInput | Prisma.TagEmbeddingWhereInput[]
  OR?: Prisma.TagEmbeddingWhereInput[]
  NOT?: Prisma.TagEmbeddingWhereInput | Prisma.TagEmbeddingWhereInput[]
  created_at?: Prisma.DateTimeFilter<"TagEmbedding"> | Date | string
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}, "id" | "tag_id">

export type TagEmbeddingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.TagEmbeddingCountOrderByAggregateInput
  _max?: Prisma.TagEmbeddingMaxOrderByAggregateInput
  _min?: Prisma.TagEmbeddingMinOrderByAggregateInput
}

export type TagEmbeddingScalarWhereWithAggregatesInput = {
  AND?: Prisma.TagEmbeddingScalarWhereWithAggregatesInput | Prisma.TagEmbeddingScalarWhereWithAggregatesInput[]
  OR?: Prisma.TagEmbeddingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TagEmbeddingScalarWhereWithAggregatesInput | Prisma.TagEmbeddingScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"TagEmbedding"> | string
  tag_id?: Prisma.UuidWithAggregatesFilter<"TagEmbedding"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"TagEmbedding"> | Date | string
}

export type TagEmbeddingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tag?: Prisma.TagUpdateOneRequiredWithoutEmbeddingNestedInput
}

export type TagEmbeddingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tag_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagEmbeddingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagEmbeddingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tag_id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagEmbeddingNullableScalarRelationFilter = {
  is?: Prisma.TagEmbeddingWhereInput | null
  isNot?: Prisma.TagEmbeddingWhereInput | null
}

export type TagEmbeddingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type TagEmbeddingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type TagEmbeddingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tag_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type TagEmbeddingCreateNestedOneWithoutTagInput = {
  connect?: Prisma.TagEmbeddingWhereUniqueInput
}

export type TagEmbeddingUncheckedCreateNestedOneWithoutTagInput = {
  connect?: Prisma.TagEmbeddingWhereUniqueInput
}

export type TagEmbeddingUpdateOneWithoutTagNestedInput = {
  disconnect?: Prisma.TagEmbeddingWhereInput | boolean
  delete?: Prisma.TagEmbeddingWhereInput | boolean
  connect?: Prisma.TagEmbeddingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TagEmbeddingUpdateToOneWithWhereWithoutTagInput, Prisma.TagEmbeddingUpdateWithoutTagInput>, Prisma.TagEmbeddingUncheckedUpdateWithoutTagInput>
}

export type TagEmbeddingUncheckedUpdateOneWithoutTagNestedInput = {
  disconnect?: Prisma.TagEmbeddingWhereInput | boolean
  delete?: Prisma.TagEmbeddingWhereInput | boolean
  connect?: Prisma.TagEmbeddingWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TagEmbeddingUpdateToOneWithWhereWithoutTagInput, Prisma.TagEmbeddingUpdateWithoutTagInput>, Prisma.TagEmbeddingUncheckedUpdateWithoutTagInput>
}

export type TagEmbeddingUpdateToOneWithWhereWithoutTagInput = {
  where?: Prisma.TagEmbeddingWhereInput
  data: Prisma.XOR<Prisma.TagEmbeddingUpdateWithoutTagInput, Prisma.TagEmbeddingUncheckedUpdateWithoutTagInput>
}

export type TagEmbeddingUpdateWithoutTagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TagEmbeddingUncheckedUpdateWithoutTagInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TagEmbeddingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tag_id?: boolean
  created_at?: boolean
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagEmbedding"]>


export type TagEmbeddingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tag_id?: boolean
  created_at?: boolean
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagEmbedding"]>

export type TagEmbeddingSelectScalar = {
  id?: boolean
  tag_id?: boolean
  created_at?: boolean
}

export type TagEmbeddingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tag_id" | "created_at", ExtArgs["result"]["tagEmbedding"]>
export type TagEmbeddingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}
export type TagEmbeddingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}

export type $TagEmbeddingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TagEmbedding"
  objects: {
    tag: Prisma.$TagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tag_id: string
    created_at: Date
  }, ExtArgs["result"]["tagEmbedding"]>
  composites: {}
}

export type TagEmbeddingGetPayload<S extends boolean | null | undefined | TagEmbeddingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TagEmbeddingPayload, S>

export type TagEmbeddingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TagEmbeddingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TagEmbeddingCountAggregateInputType | true
  }

export interface TagEmbeddingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TagEmbedding'], meta: { name: 'TagEmbedding' } }
  /**
   * Find zero or one TagEmbedding that matches the filter.
   * @param {TagEmbeddingFindUniqueArgs} args - Arguments to find a TagEmbedding
   * @example
   * // Get one TagEmbedding
   * const tagEmbedding = await prisma.tagEmbedding.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TagEmbeddingFindUniqueArgs>(args: Prisma.SelectSubset<T, TagEmbeddingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TagEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$TagEmbeddingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TagEmbedding that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TagEmbeddingFindUniqueOrThrowArgs} args - Arguments to find a TagEmbedding
   * @example
   * // Get one TagEmbedding
   * const tagEmbedding = await prisma.tagEmbedding.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TagEmbeddingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TagEmbeddingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$TagEmbeddingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagEmbedding that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagEmbeddingFindFirstArgs} args - Arguments to find a TagEmbedding
   * @example
   * // Get one TagEmbedding
   * const tagEmbedding = await prisma.tagEmbedding.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TagEmbeddingFindFirstArgs>(args?: Prisma.SelectSubset<T, TagEmbeddingFindFirstArgs<ExtArgs>>): Prisma.Prisma__TagEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$TagEmbeddingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagEmbedding that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagEmbeddingFindFirstOrThrowArgs} args - Arguments to find a TagEmbedding
   * @example
   * // Get one TagEmbedding
   * const tagEmbedding = await prisma.tagEmbedding.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TagEmbeddingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TagEmbeddingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$TagEmbeddingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TagEmbeddings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagEmbeddingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TagEmbeddings
   * const tagEmbeddings = await prisma.tagEmbedding.findMany()
   * 
   * // Get first 10 TagEmbeddings
   * const tagEmbeddings = await prisma.tagEmbedding.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tagEmbeddingWithIdOnly = await prisma.tagEmbedding.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TagEmbeddingFindManyArgs>(args?: Prisma.SelectSubset<T, TagEmbeddingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagEmbeddingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Delete a TagEmbedding.
   * @param {TagEmbeddingDeleteArgs} args - Arguments to delete one TagEmbedding.
   * @example
   * // Delete one TagEmbedding
   * const TagEmbedding = await prisma.tagEmbedding.delete({
   *   where: {
   *     // ... filter to delete one TagEmbedding
   *   }
   * })
   * 
   */
  delete<T extends TagEmbeddingDeleteArgs>(args: Prisma.SelectSubset<T, TagEmbeddingDeleteArgs<ExtArgs>>): Prisma.Prisma__TagEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$TagEmbeddingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TagEmbedding.
   * @param {TagEmbeddingUpdateArgs} args - Arguments to update one TagEmbedding.
   * @example
   * // Update one TagEmbedding
   * const tagEmbedding = await prisma.tagEmbedding.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TagEmbeddingUpdateArgs>(args: Prisma.SelectSubset<T, TagEmbeddingUpdateArgs<ExtArgs>>): Prisma.Prisma__TagEmbeddingClient<runtime.Types.Result.GetResult<Prisma.$TagEmbeddingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TagEmbeddings.
   * @param {TagEmbeddingDeleteManyArgs} args - Arguments to filter TagEmbeddings to delete.
   * @example
   * // Delete a few TagEmbeddings
   * const { count } = await prisma.tagEmbedding.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TagEmbeddingDeleteManyArgs>(args?: Prisma.SelectSubset<T, TagEmbeddingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagEmbeddings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagEmbeddingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TagEmbeddings
   * const tagEmbedding = await prisma.tagEmbedding.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TagEmbeddingUpdateManyArgs>(args: Prisma.SelectSubset<T, TagEmbeddingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagEmbeddings and returns the data updated in the database.
   * @param {TagEmbeddingUpdateManyAndReturnArgs} args - Arguments to update many TagEmbeddings.
   * @example
   * // Update many TagEmbeddings
   * const tagEmbedding = await prisma.tagEmbedding.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TagEmbeddings and only return the `id`
   * const tagEmbeddingWithIdOnly = await prisma.tagEmbedding.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TagEmbeddingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TagEmbeddingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagEmbeddingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>


  /**
   * Count the number of TagEmbeddings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagEmbeddingCountArgs} args - Arguments to filter TagEmbeddings to count.
   * @example
   * // Count the number of TagEmbeddings
   * const count = await prisma.tagEmbedding.count({
   *   where: {
   *     // ... the filter for the TagEmbeddings we want to count
   *   }
   * })
  **/
  count<T extends TagEmbeddingCountArgs>(
    args?: Prisma.Subset<T, TagEmbeddingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TagEmbeddingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TagEmbedding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagEmbeddingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TagEmbeddingAggregateArgs>(args: Prisma.Subset<T, TagEmbeddingAggregateArgs>): Prisma.PrismaPromise<GetTagEmbeddingAggregateType<T>>

  /**
   * Group by TagEmbedding.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagEmbeddingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TagEmbeddingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TagEmbeddingGroupByArgs['orderBy'] }
      : { orderBy?: TagEmbeddingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TagEmbeddingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTagEmbeddingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TagEmbedding model
 */
readonly fields: TagEmbeddingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TagEmbedding.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TagEmbeddingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tag<T extends Prisma.TagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagDefaultArgs<ExtArgs>>): Prisma.Prisma__TagClient<runtime.Types.Result.GetResult<Prisma.$TagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TagEmbedding model
 */
export interface TagEmbeddingFieldRefs {
  readonly id: Prisma.FieldRef<"TagEmbedding", 'String'>
  readonly tag_id: Prisma.FieldRef<"TagEmbedding", 'String'>
  readonly created_at: Prisma.FieldRef<"TagEmbedding", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TagEmbedding findUnique
 */
export type TagEmbeddingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagEmbedding
   */
  select?: Prisma.TagEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagEmbedding
   */
  omit?: Prisma.TagEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which TagEmbedding to fetch.
   */
  where: Prisma.TagEmbeddingWhereUniqueInput
}

/**
 * TagEmbedding findUniqueOrThrow
 */
export type TagEmbeddingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagEmbedding
   */
  select?: Prisma.TagEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagEmbedding
   */
  omit?: Prisma.TagEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which TagEmbedding to fetch.
   */
  where: Prisma.TagEmbeddingWhereUniqueInput
}

/**
 * TagEmbedding findFirst
 */
export type TagEmbeddingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagEmbedding
   */
  select?: Prisma.TagEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagEmbedding
   */
  omit?: Prisma.TagEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which TagEmbedding to fetch.
   */
  where?: Prisma.TagEmbeddingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagEmbeddings to fetch.
   */
  orderBy?: Prisma.TagEmbeddingOrderByWithRelationInput | Prisma.TagEmbeddingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagEmbeddings.
   */
  cursor?: Prisma.TagEmbeddingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagEmbeddings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagEmbeddings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagEmbeddings.
   */
  distinct?: Prisma.TagEmbeddingScalarFieldEnum | Prisma.TagEmbeddingScalarFieldEnum[]
}

/**
 * TagEmbedding findFirstOrThrow
 */
export type TagEmbeddingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagEmbedding
   */
  select?: Prisma.TagEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagEmbedding
   */
  omit?: Prisma.TagEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which TagEmbedding to fetch.
   */
  where?: Prisma.TagEmbeddingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagEmbeddings to fetch.
   */
  orderBy?: Prisma.TagEmbeddingOrderByWithRelationInput | Prisma.TagEmbeddingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagEmbeddings.
   */
  cursor?: Prisma.TagEmbeddingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagEmbeddings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagEmbeddings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagEmbeddings.
   */
  distinct?: Prisma.TagEmbeddingScalarFieldEnum | Prisma.TagEmbeddingScalarFieldEnum[]
}

/**
 * TagEmbedding findMany
 */
export type TagEmbeddingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagEmbedding
   */
  select?: Prisma.TagEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagEmbedding
   */
  omit?: Prisma.TagEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagEmbeddingInclude<ExtArgs> | null
  /**
   * Filter, which TagEmbeddings to fetch.
   */
  where?: Prisma.TagEmbeddingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagEmbeddings to fetch.
   */
  orderBy?: Prisma.TagEmbeddingOrderByWithRelationInput | Prisma.TagEmbeddingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TagEmbeddings.
   */
  cursor?: Prisma.TagEmbeddingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagEmbeddings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagEmbeddings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagEmbeddings.
   */
  distinct?: Prisma.TagEmbeddingScalarFieldEnum | Prisma.TagEmbeddingScalarFieldEnum[]
}

/**
 * TagEmbedding update
 */
export type TagEmbeddingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagEmbedding
   */
  select?: Prisma.TagEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagEmbedding
   */
  omit?: Prisma.TagEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagEmbeddingInclude<ExtArgs> | null
  /**
   * The data needed to update a TagEmbedding.
   */
  data: Prisma.XOR<Prisma.TagEmbeddingUpdateInput, Prisma.TagEmbeddingUncheckedUpdateInput>
  /**
   * Choose, which TagEmbedding to update.
   */
  where: Prisma.TagEmbeddingWhereUniqueInput
}

/**
 * TagEmbedding updateMany
 */
export type TagEmbeddingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TagEmbeddings.
   */
  data: Prisma.XOR<Prisma.TagEmbeddingUpdateManyMutationInput, Prisma.TagEmbeddingUncheckedUpdateManyInput>
  /**
   * Filter which TagEmbeddings to update
   */
  where?: Prisma.TagEmbeddingWhereInput
  /**
   * Limit how many TagEmbeddings to update.
   */
  limit?: number
}

/**
 * TagEmbedding updateManyAndReturn
 */
export type TagEmbeddingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagEmbedding
   */
  select?: Prisma.TagEmbeddingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TagEmbedding
   */
  omit?: Prisma.TagEmbeddingOmit<ExtArgs> | null
  /**
   * The data used to update TagEmbeddings.
   */
  data: Prisma.XOR<Prisma.TagEmbeddingUpdateManyMutationInput, Prisma.TagEmbeddingUncheckedUpdateManyInput>
  /**
   * Filter which TagEmbeddings to update
   */
  where?: Prisma.TagEmbeddingWhereInput
  /**
   * Limit how many TagEmbeddings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagEmbeddingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TagEmbedding delete
 */
export type TagEmbeddingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagEmbedding
   */
  select?: Prisma.TagEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagEmbedding
   */
  omit?: Prisma.TagEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagEmbeddingInclude<ExtArgs> | null
  /**
   * Filter which TagEmbedding to delete.
   */
  where: Prisma.TagEmbeddingWhereUniqueInput
}

/**
 * TagEmbedding deleteMany
 */
export type TagEmbeddingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagEmbeddings to delete
   */
  where?: Prisma.TagEmbeddingWhereInput
  /**
   * Limit how many TagEmbeddings to delete.
   */
  limit?: number
}

/**
 * TagEmbedding without action
 */
export type TagEmbeddingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagEmbedding
   */
  select?: Prisma.TagEmbeddingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagEmbedding
   */
  omit?: Prisma.TagEmbeddingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagEmbeddingInclude<ExtArgs> | null
}
