
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserQuestionStats` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserQuestionStats
 * 
 */
export type UserQuestionStatsModel = runtime.Types.Result.DefaultSelection<Prisma.$UserQuestionStatsPayload>

export type AggregateUserQuestionStats = {
  _count: UserQuestionStatsCountAggregateOutputType | null
  _avg: UserQuestionStatsAvgAggregateOutputType | null
  _sum: UserQuestionStatsSumAggregateOutputType | null
  _min: UserQuestionStatsMinAggregateOutputType | null
  _max: UserQuestionStatsMaxAggregateOutputType | null
}

export type UserQuestionStatsAvgAggregateOutputType = {
  total_attempts: number | null
  correct_count: number | null
  half_life: number | null
}

export type UserQuestionStatsSumAggregateOutputType = {
  total_attempts: number | null
  correct_count: number | null
  half_life: number | null
}

export type UserQuestionStatsMinAggregateOutputType = {
  user_id: string | null
  question_id: string | null
  total_attempts: number | null
  correct_count: number | null
  last_seen_at: Date | null
  half_life: number | null
}

export type UserQuestionStatsMaxAggregateOutputType = {
  user_id: string | null
  question_id: string | null
  total_attempts: number | null
  correct_count: number | null
  last_seen_at: Date | null
  half_life: number | null
}

export type UserQuestionStatsCountAggregateOutputType = {
  user_id: number
  question_id: number
  total_attempts: number
  correct_count: number
  last_seen_at: number
  half_life: number
  _all: number
}


export type UserQuestionStatsAvgAggregateInputType = {
  total_attempts?: true
  correct_count?: true
  half_life?: true
}

export type UserQuestionStatsSumAggregateInputType = {
  total_attempts?: true
  correct_count?: true
  half_life?: true
}

export type UserQuestionStatsMinAggregateInputType = {
  user_id?: true
  question_id?: true
  total_attempts?: true
  correct_count?: true
  last_seen_at?: true
  half_life?: true
}

export type UserQuestionStatsMaxAggregateInputType = {
  user_id?: true
  question_id?: true
  total_attempts?: true
  correct_count?: true
  last_seen_at?: true
  half_life?: true
}

export type UserQuestionStatsCountAggregateInputType = {
  user_id?: true
  question_id?: true
  total_attempts?: true
  correct_count?: true
  last_seen_at?: true
  half_life?: true
  _all?: true
}

export type UserQuestionStatsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserQuestionStats to aggregate.
   */
  where?: Prisma.UserQuestionStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserQuestionStats to fetch.
   */
  orderBy?: Prisma.UserQuestionStatsOrderByWithRelationInput | Prisma.UserQuestionStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserQuestionStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserQuestionStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserQuestionStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserQuestionStats
  **/
  _count?: true | UserQuestionStatsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserQuestionStatsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserQuestionStatsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserQuestionStatsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserQuestionStatsMaxAggregateInputType
}

export type GetUserQuestionStatsAggregateType<T extends UserQuestionStatsAggregateArgs> = {
      [P in keyof T & keyof AggregateUserQuestionStats]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserQuestionStats[P]>
    : Prisma.GetScalarType<T[P], AggregateUserQuestionStats[P]>
}




export type UserQuestionStatsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserQuestionStatsWhereInput
  orderBy?: Prisma.UserQuestionStatsOrderByWithAggregationInput | Prisma.UserQuestionStatsOrderByWithAggregationInput[]
  by: Prisma.UserQuestionStatsScalarFieldEnum[] | Prisma.UserQuestionStatsScalarFieldEnum
  having?: Prisma.UserQuestionStatsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserQuestionStatsCountAggregateInputType | true
  _avg?: UserQuestionStatsAvgAggregateInputType
  _sum?: UserQuestionStatsSumAggregateInputType
  _min?: UserQuestionStatsMinAggregateInputType
  _max?: UserQuestionStatsMaxAggregateInputType
}

export type UserQuestionStatsGroupByOutputType = {
  user_id: string
  question_id: string
  total_attempts: number
  correct_count: number
  last_seen_at: Date
  half_life: number
  _count: UserQuestionStatsCountAggregateOutputType | null
  _avg: UserQuestionStatsAvgAggregateOutputType | null
  _sum: UserQuestionStatsSumAggregateOutputType | null
  _min: UserQuestionStatsMinAggregateOutputType | null
  _max: UserQuestionStatsMaxAggregateOutputType | null
}

export type GetUserQuestionStatsGroupByPayload<T extends UserQuestionStatsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserQuestionStatsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserQuestionStatsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserQuestionStatsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserQuestionStatsGroupByOutputType[P]>
      }
    >
  >



export type UserQuestionStatsWhereInput = {
  AND?: Prisma.UserQuestionStatsWhereInput | Prisma.UserQuestionStatsWhereInput[]
  OR?: Prisma.UserQuestionStatsWhereInput[]
  NOT?: Prisma.UserQuestionStatsWhereInput | Prisma.UserQuestionStatsWhereInput[]
  user_id?: Prisma.UuidFilter<"UserQuestionStats"> | string
  question_id?: Prisma.UuidFilter<"UserQuestionStats"> | string
  total_attempts?: Prisma.IntFilter<"UserQuestionStats"> | number
  correct_count?: Prisma.IntFilter<"UserQuestionStats"> | number
  last_seen_at?: Prisma.DateTimeFilter<"UserQuestionStats"> | Date | string
  half_life?: Prisma.FloatFilter<"UserQuestionStats"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
}

export type UserQuestionStatsOrderByWithRelationInput = {
  user_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  total_attempts?: Prisma.SortOrder
  correct_count?: Prisma.SortOrder
  last_seen_at?: Prisma.SortOrder
  half_life?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  question?: Prisma.QuestionOrderByWithRelationInput
}

export type UserQuestionStatsWhereUniqueInput = Prisma.AtLeast<{
  user_id_question_id?: Prisma.UserQuestionStatsUser_idQuestion_idCompoundUniqueInput
  AND?: Prisma.UserQuestionStatsWhereInput | Prisma.UserQuestionStatsWhereInput[]
  OR?: Prisma.UserQuestionStatsWhereInput[]
  NOT?: Prisma.UserQuestionStatsWhereInput | Prisma.UserQuestionStatsWhereInput[]
  user_id?: Prisma.UuidFilter<"UserQuestionStats"> | string
  question_id?: Prisma.UuidFilter<"UserQuestionStats"> | string
  total_attempts?: Prisma.IntFilter<"UserQuestionStats"> | number
  correct_count?: Prisma.IntFilter<"UserQuestionStats"> | number
  last_seen_at?: Prisma.DateTimeFilter<"UserQuestionStats"> | Date | string
  half_life?: Prisma.FloatFilter<"UserQuestionStats"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
}, "user_id_question_id">

export type UserQuestionStatsOrderByWithAggregationInput = {
  user_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  total_attempts?: Prisma.SortOrder
  correct_count?: Prisma.SortOrder
  last_seen_at?: Prisma.SortOrder
  half_life?: Prisma.SortOrder
  _count?: Prisma.UserQuestionStatsCountOrderByAggregateInput
  _avg?: Prisma.UserQuestionStatsAvgOrderByAggregateInput
  _max?: Prisma.UserQuestionStatsMaxOrderByAggregateInput
  _min?: Prisma.UserQuestionStatsMinOrderByAggregateInput
  _sum?: Prisma.UserQuestionStatsSumOrderByAggregateInput
}

export type UserQuestionStatsScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserQuestionStatsScalarWhereWithAggregatesInput | Prisma.UserQuestionStatsScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserQuestionStatsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserQuestionStatsScalarWhereWithAggregatesInput | Prisma.UserQuestionStatsScalarWhereWithAggregatesInput[]
  user_id?: Prisma.UuidWithAggregatesFilter<"UserQuestionStats"> | string
  question_id?: Prisma.UuidWithAggregatesFilter<"UserQuestionStats"> | string
  total_attempts?: Prisma.IntWithAggregatesFilter<"UserQuestionStats"> | number
  correct_count?: Prisma.IntWithAggregatesFilter<"UserQuestionStats"> | number
  last_seen_at?: Prisma.DateTimeWithAggregatesFilter<"UserQuestionStats"> | Date | string
  half_life?: Prisma.FloatWithAggregatesFilter<"UserQuestionStats"> | number
}

export type UserQuestionStatsCreateInput = {
  total_attempts?: number
  correct_count?: number
  last_seen_at: Date | string
  half_life?: number
  user: Prisma.UserCreateNestedOneWithoutQuestion_statsInput
  question: Prisma.QuestionCreateNestedOneWithoutQuestion_statsInput
}

export type UserQuestionStatsUncheckedCreateInput = {
  user_id: string
  question_id: string
  total_attempts?: number
  correct_count?: number
  last_seen_at: Date | string
  half_life?: number
}

export type UserQuestionStatsUpdateInput = {
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutQuestion_statsNestedInput
  question?: Prisma.QuestionUpdateOneRequiredWithoutQuestion_statsNestedInput
}

export type UserQuestionStatsUncheckedUpdateInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type UserQuestionStatsCreateManyInput = {
  user_id: string
  question_id: string
  total_attempts?: number
  correct_count?: number
  last_seen_at: Date | string
  half_life?: number
}

export type UserQuestionStatsUpdateManyMutationInput = {
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type UserQuestionStatsUncheckedUpdateManyInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type UserQuestionStatsListRelationFilter = {
  every?: Prisma.UserQuestionStatsWhereInput
  some?: Prisma.UserQuestionStatsWhereInput
  none?: Prisma.UserQuestionStatsWhereInput
}

export type UserQuestionStatsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserQuestionStatsUser_idQuestion_idCompoundUniqueInput = {
  user_id: string
  question_id: string
}

export type UserQuestionStatsCountOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  total_attempts?: Prisma.SortOrder
  correct_count?: Prisma.SortOrder
  last_seen_at?: Prisma.SortOrder
  half_life?: Prisma.SortOrder
}

export type UserQuestionStatsAvgOrderByAggregateInput = {
  total_attempts?: Prisma.SortOrder
  correct_count?: Prisma.SortOrder
  half_life?: Prisma.SortOrder
}

export type UserQuestionStatsMaxOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  total_attempts?: Prisma.SortOrder
  correct_count?: Prisma.SortOrder
  last_seen_at?: Prisma.SortOrder
  half_life?: Prisma.SortOrder
}

export type UserQuestionStatsMinOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
  question_id?: Prisma.SortOrder
  total_attempts?: Prisma.SortOrder
  correct_count?: Prisma.SortOrder
  last_seen_at?: Prisma.SortOrder
  half_life?: Prisma.SortOrder
}

export type UserQuestionStatsSumOrderByAggregateInput = {
  total_attempts?: Prisma.SortOrder
  correct_count?: Prisma.SortOrder
  half_life?: Prisma.SortOrder
}

export type UserQuestionStatsCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutUserInput, Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput> | Prisma.UserQuestionStatsCreateWithoutUserInput[] | Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserQuestionStatsCreateOrConnectWithoutUserInput | Prisma.UserQuestionStatsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserQuestionStatsCreateManyUserInputEnvelope
  connect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
}

export type UserQuestionStatsUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutUserInput, Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput> | Prisma.UserQuestionStatsCreateWithoutUserInput[] | Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserQuestionStatsCreateOrConnectWithoutUserInput | Prisma.UserQuestionStatsCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserQuestionStatsCreateManyUserInputEnvelope
  connect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
}

export type UserQuestionStatsUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutUserInput, Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput> | Prisma.UserQuestionStatsCreateWithoutUserInput[] | Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserQuestionStatsCreateOrConnectWithoutUserInput | Prisma.UserQuestionStatsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserQuestionStatsUpsertWithWhereUniqueWithoutUserInput | Prisma.UserQuestionStatsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserQuestionStatsCreateManyUserInputEnvelope
  set?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  disconnect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  delete?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  connect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  update?: Prisma.UserQuestionStatsUpdateWithWhereUniqueWithoutUserInput | Prisma.UserQuestionStatsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserQuestionStatsUpdateManyWithWhereWithoutUserInput | Prisma.UserQuestionStatsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserQuestionStatsScalarWhereInput | Prisma.UserQuestionStatsScalarWhereInput[]
}

export type UserQuestionStatsUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutUserInput, Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput> | Prisma.UserQuestionStatsCreateWithoutUserInput[] | Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserQuestionStatsCreateOrConnectWithoutUserInput | Prisma.UserQuestionStatsCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserQuestionStatsUpsertWithWhereUniqueWithoutUserInput | Prisma.UserQuestionStatsUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserQuestionStatsCreateManyUserInputEnvelope
  set?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  disconnect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  delete?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  connect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  update?: Prisma.UserQuestionStatsUpdateWithWhereUniqueWithoutUserInput | Prisma.UserQuestionStatsUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserQuestionStatsUpdateManyWithWhereWithoutUserInput | Prisma.UserQuestionStatsUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserQuestionStatsScalarWhereInput | Prisma.UserQuestionStatsScalarWhereInput[]
}

export type UserQuestionStatsCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutQuestionInput, Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput> | Prisma.UserQuestionStatsCreateWithoutQuestionInput[] | Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.UserQuestionStatsCreateOrConnectWithoutQuestionInput | Prisma.UserQuestionStatsCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.UserQuestionStatsCreateManyQuestionInputEnvelope
  connect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
}

export type UserQuestionStatsUncheckedCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutQuestionInput, Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput> | Prisma.UserQuestionStatsCreateWithoutQuestionInput[] | Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.UserQuestionStatsCreateOrConnectWithoutQuestionInput | Prisma.UserQuestionStatsCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.UserQuestionStatsCreateManyQuestionInputEnvelope
  connect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
}

export type UserQuestionStatsUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutQuestionInput, Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput> | Prisma.UserQuestionStatsCreateWithoutQuestionInput[] | Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.UserQuestionStatsCreateOrConnectWithoutQuestionInput | Prisma.UserQuestionStatsCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.UserQuestionStatsUpsertWithWhereUniqueWithoutQuestionInput | Prisma.UserQuestionStatsUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.UserQuestionStatsCreateManyQuestionInputEnvelope
  set?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  disconnect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  delete?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  connect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  update?: Prisma.UserQuestionStatsUpdateWithWhereUniqueWithoutQuestionInput | Prisma.UserQuestionStatsUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.UserQuestionStatsUpdateManyWithWhereWithoutQuestionInput | Prisma.UserQuestionStatsUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.UserQuestionStatsScalarWhereInput | Prisma.UserQuestionStatsScalarWhereInput[]
}

export type UserQuestionStatsUncheckedUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutQuestionInput, Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput> | Prisma.UserQuestionStatsCreateWithoutQuestionInput[] | Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.UserQuestionStatsCreateOrConnectWithoutQuestionInput | Prisma.UserQuestionStatsCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.UserQuestionStatsUpsertWithWhereUniqueWithoutQuestionInput | Prisma.UserQuestionStatsUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.UserQuestionStatsCreateManyQuestionInputEnvelope
  set?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  disconnect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  delete?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  connect?: Prisma.UserQuestionStatsWhereUniqueInput | Prisma.UserQuestionStatsWhereUniqueInput[]
  update?: Prisma.UserQuestionStatsUpdateWithWhereUniqueWithoutQuestionInput | Prisma.UserQuestionStatsUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.UserQuestionStatsUpdateManyWithWhereWithoutQuestionInput | Prisma.UserQuestionStatsUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.UserQuestionStatsScalarWhereInput | Prisma.UserQuestionStatsScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type UserQuestionStatsCreateWithoutUserInput = {
  total_attempts?: number
  correct_count?: number
  last_seen_at: Date | string
  half_life?: number
  question: Prisma.QuestionCreateNestedOneWithoutQuestion_statsInput
}

export type UserQuestionStatsUncheckedCreateWithoutUserInput = {
  question_id: string
  total_attempts?: number
  correct_count?: number
  last_seen_at: Date | string
  half_life?: number
}

export type UserQuestionStatsCreateOrConnectWithoutUserInput = {
  where: Prisma.UserQuestionStatsWhereUniqueInput
  create: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutUserInput, Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput>
}

export type UserQuestionStatsCreateManyUserInputEnvelope = {
  data: Prisma.UserQuestionStatsCreateManyUserInput | Prisma.UserQuestionStatsCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserQuestionStatsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserQuestionStatsWhereUniqueInput
  update: Prisma.XOR<Prisma.UserQuestionStatsUpdateWithoutUserInput, Prisma.UserQuestionStatsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutUserInput, Prisma.UserQuestionStatsUncheckedCreateWithoutUserInput>
}

export type UserQuestionStatsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserQuestionStatsWhereUniqueInput
  data: Prisma.XOR<Prisma.UserQuestionStatsUpdateWithoutUserInput, Prisma.UserQuestionStatsUncheckedUpdateWithoutUserInput>
}

export type UserQuestionStatsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserQuestionStatsScalarWhereInput
  data: Prisma.XOR<Prisma.UserQuestionStatsUpdateManyMutationInput, Prisma.UserQuestionStatsUncheckedUpdateManyWithoutUserInput>
}

export type UserQuestionStatsScalarWhereInput = {
  AND?: Prisma.UserQuestionStatsScalarWhereInput | Prisma.UserQuestionStatsScalarWhereInput[]
  OR?: Prisma.UserQuestionStatsScalarWhereInput[]
  NOT?: Prisma.UserQuestionStatsScalarWhereInput | Prisma.UserQuestionStatsScalarWhereInput[]
  user_id?: Prisma.UuidFilter<"UserQuestionStats"> | string
  question_id?: Prisma.UuidFilter<"UserQuestionStats"> | string
  total_attempts?: Prisma.IntFilter<"UserQuestionStats"> | number
  correct_count?: Prisma.IntFilter<"UserQuestionStats"> | number
  last_seen_at?: Prisma.DateTimeFilter<"UserQuestionStats"> | Date | string
  half_life?: Prisma.FloatFilter<"UserQuestionStats"> | number
}

export type UserQuestionStatsCreateWithoutQuestionInput = {
  total_attempts?: number
  correct_count?: number
  last_seen_at: Date | string
  half_life?: number
  user: Prisma.UserCreateNestedOneWithoutQuestion_statsInput
}

export type UserQuestionStatsUncheckedCreateWithoutQuestionInput = {
  user_id: string
  total_attempts?: number
  correct_count?: number
  last_seen_at: Date | string
  half_life?: number
}

export type UserQuestionStatsCreateOrConnectWithoutQuestionInput = {
  where: Prisma.UserQuestionStatsWhereUniqueInput
  create: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutQuestionInput, Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput>
}

export type UserQuestionStatsCreateManyQuestionInputEnvelope = {
  data: Prisma.UserQuestionStatsCreateManyQuestionInput | Prisma.UserQuestionStatsCreateManyQuestionInput[]
  skipDuplicates?: boolean
}

export type UserQuestionStatsUpsertWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.UserQuestionStatsWhereUniqueInput
  update: Prisma.XOR<Prisma.UserQuestionStatsUpdateWithoutQuestionInput, Prisma.UserQuestionStatsUncheckedUpdateWithoutQuestionInput>
  create: Prisma.XOR<Prisma.UserQuestionStatsCreateWithoutQuestionInput, Prisma.UserQuestionStatsUncheckedCreateWithoutQuestionInput>
}

export type UserQuestionStatsUpdateWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.UserQuestionStatsWhereUniqueInput
  data: Prisma.XOR<Prisma.UserQuestionStatsUpdateWithoutQuestionInput, Prisma.UserQuestionStatsUncheckedUpdateWithoutQuestionInput>
}

export type UserQuestionStatsUpdateManyWithWhereWithoutQuestionInput = {
  where: Prisma.UserQuestionStatsScalarWhereInput
  data: Prisma.XOR<Prisma.UserQuestionStatsUpdateManyMutationInput, Prisma.UserQuestionStatsUncheckedUpdateManyWithoutQuestionInput>
}

export type UserQuestionStatsCreateManyUserInput = {
  question_id: string
  total_attempts?: number
  correct_count?: number
  last_seen_at: Date | string
  half_life?: number
}

export type UserQuestionStatsUpdateWithoutUserInput = {
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
  question?: Prisma.QuestionUpdateOneRequiredWithoutQuestion_statsNestedInput
}

export type UserQuestionStatsUncheckedUpdateWithoutUserInput = {
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type UserQuestionStatsUncheckedUpdateManyWithoutUserInput = {
  question_id?: Prisma.StringFieldUpdateOperationsInput | string
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type UserQuestionStatsCreateManyQuestionInput = {
  user_id: string
  total_attempts?: number
  correct_count?: number
  last_seen_at: Date | string
  half_life?: number
}

export type UserQuestionStatsUpdateWithoutQuestionInput = {
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutQuestion_statsNestedInput
}

export type UserQuestionStatsUncheckedUpdateWithoutQuestionInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type UserQuestionStatsUncheckedUpdateManyWithoutQuestionInput = {
  user_id?: Prisma.StringFieldUpdateOperationsInput | string
  total_attempts?: Prisma.IntFieldUpdateOperationsInput | number
  correct_count?: Prisma.IntFieldUpdateOperationsInput | number
  last_seen_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  half_life?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type UserQuestionStatsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  question_id?: boolean
  total_attempts?: boolean
  correct_count?: boolean
  last_seen_at?: boolean
  half_life?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userQuestionStats"]>

export type UserQuestionStatsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  question_id?: boolean
  total_attempts?: boolean
  correct_count?: boolean
  last_seen_at?: boolean
  half_life?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userQuestionStats"]>

export type UserQuestionStatsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  user_id?: boolean
  question_id?: boolean
  total_attempts?: boolean
  correct_count?: boolean
  last_seen_at?: boolean
  half_life?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userQuestionStats"]>

export type UserQuestionStatsSelectScalar = {
  user_id?: boolean
  question_id?: boolean
  total_attempts?: boolean
  correct_count?: boolean
  last_seen_at?: boolean
  half_life?: boolean
}

export type UserQuestionStatsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"user_id" | "question_id" | "total_attempts" | "correct_count" | "last_seen_at" | "half_life", ExtArgs["result"]["userQuestionStats"]>
export type UserQuestionStatsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}
export type UserQuestionStatsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}
export type UserQuestionStatsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}

export type $UserQuestionStatsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserQuestionStats"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    question: Prisma.$QuestionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    user_id: string
    question_id: string
    total_attempts: number
    correct_count: number
    last_seen_at: Date
    half_life: number
  }, ExtArgs["result"]["userQuestionStats"]>
  composites: {}
}

export type UserQuestionStatsGetPayload<S extends boolean | null | undefined | UserQuestionStatsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload, S>

export type UserQuestionStatsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserQuestionStatsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserQuestionStatsCountAggregateInputType | true
  }

export interface UserQuestionStatsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserQuestionStats'], meta: { name: 'UserQuestionStats' } }
  /**
   * Find zero or one UserQuestionStats that matches the filter.
   * @param {UserQuestionStatsFindUniqueArgs} args - Arguments to find a UserQuestionStats
   * @example
   * // Get one UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserQuestionStatsFindUniqueArgs>(args: Prisma.SelectSubset<T, UserQuestionStatsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserQuestionStatsClient<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserQuestionStats that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserQuestionStatsFindUniqueOrThrowArgs} args - Arguments to find a UserQuestionStats
   * @example
   * // Get one UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserQuestionStatsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserQuestionStatsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserQuestionStatsClient<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserQuestionStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserQuestionStatsFindFirstArgs} args - Arguments to find a UserQuestionStats
   * @example
   * // Get one UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserQuestionStatsFindFirstArgs>(args?: Prisma.SelectSubset<T, UserQuestionStatsFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserQuestionStatsClient<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserQuestionStats that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserQuestionStatsFindFirstOrThrowArgs} args - Arguments to find a UserQuestionStats
   * @example
   * // Get one UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserQuestionStatsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserQuestionStatsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserQuestionStatsClient<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserQuestionStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserQuestionStatsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.findMany()
   * 
   * // Get first 10 UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.findMany({ take: 10 })
   * 
   * // Only select the `user_id`
   * const userQuestionStatsWithUser_idOnly = await prisma.userQuestionStats.findMany({ select: { user_id: true } })
   * 
   */
  findMany<T extends UserQuestionStatsFindManyArgs>(args?: Prisma.SelectSubset<T, UserQuestionStatsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserQuestionStats.
   * @param {UserQuestionStatsCreateArgs} args - Arguments to create a UserQuestionStats.
   * @example
   * // Create one UserQuestionStats
   * const UserQuestionStats = await prisma.userQuestionStats.create({
   *   data: {
   *     // ... data to create a UserQuestionStats
   *   }
   * })
   * 
   */
  create<T extends UserQuestionStatsCreateArgs>(args: Prisma.SelectSubset<T, UserQuestionStatsCreateArgs<ExtArgs>>): Prisma.Prisma__UserQuestionStatsClient<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserQuestionStats.
   * @param {UserQuestionStatsCreateManyArgs} args - Arguments to create many UserQuestionStats.
   * @example
   * // Create many UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserQuestionStatsCreateManyArgs>(args?: Prisma.SelectSubset<T, UserQuestionStatsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserQuestionStats and returns the data saved in the database.
   * @param {UserQuestionStatsCreateManyAndReturnArgs} args - Arguments to create many UserQuestionStats.
   * @example
   * // Create many UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserQuestionStats and only return the `user_id`
   * const userQuestionStatsWithUser_idOnly = await prisma.userQuestionStats.createManyAndReturn({
   *   select: { user_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserQuestionStatsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserQuestionStatsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserQuestionStats.
   * @param {UserQuestionStatsDeleteArgs} args - Arguments to delete one UserQuestionStats.
   * @example
   * // Delete one UserQuestionStats
   * const UserQuestionStats = await prisma.userQuestionStats.delete({
   *   where: {
   *     // ... filter to delete one UserQuestionStats
   *   }
   * })
   * 
   */
  delete<T extends UserQuestionStatsDeleteArgs>(args: Prisma.SelectSubset<T, UserQuestionStatsDeleteArgs<ExtArgs>>): Prisma.Prisma__UserQuestionStatsClient<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserQuestionStats.
   * @param {UserQuestionStatsUpdateArgs} args - Arguments to update one UserQuestionStats.
   * @example
   * // Update one UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserQuestionStatsUpdateArgs>(args: Prisma.SelectSubset<T, UserQuestionStatsUpdateArgs<ExtArgs>>): Prisma.Prisma__UserQuestionStatsClient<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserQuestionStats.
   * @param {UserQuestionStatsDeleteManyArgs} args - Arguments to filter UserQuestionStats to delete.
   * @example
   * // Delete a few UserQuestionStats
   * const { count } = await prisma.userQuestionStats.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserQuestionStatsDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserQuestionStatsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserQuestionStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserQuestionStatsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserQuestionStatsUpdateManyArgs>(args: Prisma.SelectSubset<T, UserQuestionStatsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserQuestionStats and returns the data updated in the database.
   * @param {UserQuestionStatsUpdateManyAndReturnArgs} args - Arguments to update many UserQuestionStats.
   * @example
   * // Update many UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserQuestionStats and only return the `user_id`
   * const userQuestionStatsWithUser_idOnly = await prisma.userQuestionStats.updateManyAndReturn({
   *   select: { user_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserQuestionStatsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserQuestionStatsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserQuestionStats.
   * @param {UserQuestionStatsUpsertArgs} args - Arguments to update or create a UserQuestionStats.
   * @example
   * // Update or create a UserQuestionStats
   * const userQuestionStats = await prisma.userQuestionStats.upsert({
   *   create: {
   *     // ... data to create a UserQuestionStats
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserQuestionStats we want to update
   *   }
   * })
   */
  upsert<T extends UserQuestionStatsUpsertArgs>(args: Prisma.SelectSubset<T, UserQuestionStatsUpsertArgs<ExtArgs>>): Prisma.Prisma__UserQuestionStatsClient<runtime.Types.Result.GetResult<Prisma.$UserQuestionStatsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserQuestionStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserQuestionStatsCountArgs} args - Arguments to filter UserQuestionStats to count.
   * @example
   * // Count the number of UserQuestionStats
   * const count = await prisma.userQuestionStats.count({
   *   where: {
   *     // ... the filter for the UserQuestionStats we want to count
   *   }
   * })
  **/
  count<T extends UserQuestionStatsCountArgs>(
    args?: Prisma.Subset<T, UserQuestionStatsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserQuestionStatsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserQuestionStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserQuestionStatsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserQuestionStatsAggregateArgs>(args: Prisma.Subset<T, UserQuestionStatsAggregateArgs>): Prisma.PrismaPromise<GetUserQuestionStatsAggregateType<T>>

  /**
   * Group by UserQuestionStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserQuestionStatsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserQuestionStatsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserQuestionStatsGroupByArgs['orderBy'] }
      : { orderBy?: UserQuestionStatsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserQuestionStatsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserQuestionStatsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserQuestionStats model
 */
readonly fields: UserQuestionStatsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserQuestionStats.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserQuestionStatsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  question<T extends Prisma.QuestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuestionDefaultArgs<ExtArgs>>): Prisma.Prisma__QuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserQuestionStats model
 */
export interface UserQuestionStatsFieldRefs {
  readonly user_id: Prisma.FieldRef<"UserQuestionStats", 'String'>
  readonly question_id: Prisma.FieldRef<"UserQuestionStats", 'String'>
  readonly total_attempts: Prisma.FieldRef<"UserQuestionStats", 'Int'>
  readonly correct_count: Prisma.FieldRef<"UserQuestionStats", 'Int'>
  readonly last_seen_at: Prisma.FieldRef<"UserQuestionStats", 'DateTime'>
  readonly half_life: Prisma.FieldRef<"UserQuestionStats", 'Float'>
}
    

// Custom InputTypes
/**
 * UserQuestionStats findUnique
 */
export type UserQuestionStatsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
  /**
   * Filter, which UserQuestionStats to fetch.
   */
  where: Prisma.UserQuestionStatsWhereUniqueInput
}

/**
 * UserQuestionStats findUniqueOrThrow
 */
export type UserQuestionStatsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
  /**
   * Filter, which UserQuestionStats to fetch.
   */
  where: Prisma.UserQuestionStatsWhereUniqueInput
}

/**
 * UserQuestionStats findFirst
 */
export type UserQuestionStatsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
  /**
   * Filter, which UserQuestionStats to fetch.
   */
  where?: Prisma.UserQuestionStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserQuestionStats to fetch.
   */
  orderBy?: Prisma.UserQuestionStatsOrderByWithRelationInput | Prisma.UserQuestionStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserQuestionStats.
   */
  cursor?: Prisma.UserQuestionStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserQuestionStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserQuestionStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserQuestionStats.
   */
  distinct?: Prisma.UserQuestionStatsScalarFieldEnum | Prisma.UserQuestionStatsScalarFieldEnum[]
}

/**
 * UserQuestionStats findFirstOrThrow
 */
export type UserQuestionStatsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
  /**
   * Filter, which UserQuestionStats to fetch.
   */
  where?: Prisma.UserQuestionStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserQuestionStats to fetch.
   */
  orderBy?: Prisma.UserQuestionStatsOrderByWithRelationInput | Prisma.UserQuestionStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserQuestionStats.
   */
  cursor?: Prisma.UserQuestionStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserQuestionStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserQuestionStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserQuestionStats.
   */
  distinct?: Prisma.UserQuestionStatsScalarFieldEnum | Prisma.UserQuestionStatsScalarFieldEnum[]
}

/**
 * UserQuestionStats findMany
 */
export type UserQuestionStatsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
  /**
   * Filter, which UserQuestionStats to fetch.
   */
  where?: Prisma.UserQuestionStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserQuestionStats to fetch.
   */
  orderBy?: Prisma.UserQuestionStatsOrderByWithRelationInput | Prisma.UserQuestionStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserQuestionStats.
   */
  cursor?: Prisma.UserQuestionStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserQuestionStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserQuestionStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserQuestionStats.
   */
  distinct?: Prisma.UserQuestionStatsScalarFieldEnum | Prisma.UserQuestionStatsScalarFieldEnum[]
}

/**
 * UserQuestionStats create
 */
export type UserQuestionStatsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
  /**
   * The data needed to create a UserQuestionStats.
   */
  data: Prisma.XOR<Prisma.UserQuestionStatsCreateInput, Prisma.UserQuestionStatsUncheckedCreateInput>
}

/**
 * UserQuestionStats createMany
 */
export type UserQuestionStatsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserQuestionStats.
   */
  data: Prisma.UserQuestionStatsCreateManyInput | Prisma.UserQuestionStatsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserQuestionStats createManyAndReturn
 */
export type UserQuestionStatsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * The data used to create many UserQuestionStats.
   */
  data: Prisma.UserQuestionStatsCreateManyInput | Prisma.UserQuestionStatsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserQuestionStats update
 */
export type UserQuestionStatsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
  /**
   * The data needed to update a UserQuestionStats.
   */
  data: Prisma.XOR<Prisma.UserQuestionStatsUpdateInput, Prisma.UserQuestionStatsUncheckedUpdateInput>
  /**
   * Choose, which UserQuestionStats to update.
   */
  where: Prisma.UserQuestionStatsWhereUniqueInput
}

/**
 * UserQuestionStats updateMany
 */
export type UserQuestionStatsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserQuestionStats.
   */
  data: Prisma.XOR<Prisma.UserQuestionStatsUpdateManyMutationInput, Prisma.UserQuestionStatsUncheckedUpdateManyInput>
  /**
   * Filter which UserQuestionStats to update
   */
  where?: Prisma.UserQuestionStatsWhereInput
  /**
   * Limit how many UserQuestionStats to update.
   */
  limit?: number
}

/**
 * UserQuestionStats updateManyAndReturn
 */
export type UserQuestionStatsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * The data used to update UserQuestionStats.
   */
  data: Prisma.XOR<Prisma.UserQuestionStatsUpdateManyMutationInput, Prisma.UserQuestionStatsUncheckedUpdateManyInput>
  /**
   * Filter which UserQuestionStats to update
   */
  where?: Prisma.UserQuestionStatsWhereInput
  /**
   * Limit how many UserQuestionStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserQuestionStats upsert
 */
export type UserQuestionStatsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
  /**
   * The filter to search for the UserQuestionStats to update in case it exists.
   */
  where: Prisma.UserQuestionStatsWhereUniqueInput
  /**
   * In case the UserQuestionStats found by the `where` argument doesn't exist, create a new UserQuestionStats with this data.
   */
  create: Prisma.XOR<Prisma.UserQuestionStatsCreateInput, Prisma.UserQuestionStatsUncheckedCreateInput>
  /**
   * In case the UserQuestionStats was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserQuestionStatsUpdateInput, Prisma.UserQuestionStatsUncheckedUpdateInput>
}

/**
 * UserQuestionStats delete
 */
export type UserQuestionStatsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
  /**
   * Filter which UserQuestionStats to delete.
   */
  where: Prisma.UserQuestionStatsWhereUniqueInput
}

/**
 * UserQuestionStats deleteMany
 */
export type UserQuestionStatsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserQuestionStats to delete
   */
  where?: Prisma.UserQuestionStatsWhereInput
  /**
   * Limit how many UserQuestionStats to delete.
   */
  limit?: number
}

/**
 * UserQuestionStats without action
 */
export type UserQuestionStatsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserQuestionStats
   */
  select?: Prisma.UserQuestionStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserQuestionStats
   */
  omit?: Prisma.UserQuestionStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserQuestionStatsInclude<ExtArgs> | null
}
